# -*- coding: utf-8 -*-
"""Dünya Kaşifi için elle yazılmış Türkçe içerik."""

# Türkçe başkent adları (listede olmayanlar kaynak veriden aynen alınır)
CAPITAL_TR = {
    'AT': 'Viyana', 'BE': 'Brüksel', 'CN': 'Pekin', 'EG': 'Kahire', 'DK': 'Kopenhag',
    'DZ': 'Cezayir', 'GR': 'Atina', 'ET': 'Addis Ababa', 'GB': 'Londra', 'GE': 'Tiflis',
    'IT': 'Roma', 'KW': 'Kuveyt', 'RU': 'Moskova', 'PL': 'Varşova', 'PT': 'Lizbon',
    'RO': 'Bükreş', 'SA': 'Riyad', 'RS': 'Belgrad', 'SY': 'Şam', 'UA': 'Kiev',
    'US': 'Washington', 'UZ': 'Taşkent', 'YE': 'Sana', 'CZ': 'Prag', 'IQ': 'Bağdat',
    'IR': 'Tahran', 'AZ': 'Bakü', 'MX': 'Meksiko', 'BR': 'Brasilia', 'CO': 'Bogota',
    'BD': 'Dakka', 'IN': 'Yeni Delhi', 'KR': 'Seul', 'TM': 'Aşkabat', 'KG': 'Bişkek',
    'TJ': 'Duşanbe', 'AM': 'Erivan', 'CY': 'Lefkoşa', 'MD': 'Kişinev', 'MK': 'Üsküp',
    'BA': 'Saraybosna', 'AL': 'Tiran', 'BG': 'Sofya', 'HU': 'Budapeşte', 'LU': 'Lüksemburg',
    'MC': 'Monako', 'VA': 'Vatikan', 'SM': 'San Marino', 'TN': 'Tunus', 'LY': 'Trablus',
    'SD': 'Hartum', 'SO': 'Mogadişu', 'OM': 'Maskat', 'LB': 'Beyrut', 'NP': 'Katmandu',
    'BT': 'Timpu', 'MV': 'Male', 'MM': 'Neypido', 'SG': 'Singapur', 'ID': 'Cakarta',
    'MN': 'Ulan Batur', 'GT': 'Guatemala', 'PA': 'Panama', 'EC': 'Kito', 'PY': 'Asuncion',
    'VE': 'Karakas', 'CM': 'Yaounde', 'CD': 'Kinşasa', 'CI': 'Yamusukro', 'NA': 'Windhoek',
    'GH': 'Akra', 'TD': 'Encamena', 'MR': 'Nuakşot', 'BF': 'Vagadugu', 'GN': 'Konakri',
    'DJ': 'Cibuti', 'SS': 'Cuba', 'KI': 'Güney Tarawa', 'BO': 'Sucre', 'KZ': 'Astana',
    'XK': 'Priştine', 'IL': 'Kudüs', 'PS': 'Ramallah', 'TW': 'Taipei', 'KP': 'Pyongyang',
    'LA': 'Vientiane', 'KH': 'Phnom Penh', 'TH': 'Bangkok', 'VN': 'Hanoi', 'PH': 'Manila',
    'MY': 'Kuala Lumpur', 'BN': 'Bandar Seri Begawan', 'PK': 'İslamabad', 'AF': 'Kabil',
    'JO': 'Amman', 'AE': 'Abu Dabi', 'QA': 'Doha', 'BH': 'Manama', 'CH': 'Bern',
    'NL': 'Amsterdam', 'ZA': 'Pretoria', 'WS': 'Apia', 'TO': "Nuku'alofa", 'ST': 'São Tomé',
    'CV': 'Praia', 'GQ': 'Malabo', 'KM': 'Moroni', 'SC': 'Victoria', 'MU': 'Port Louis',
    'SZ': 'Mbabane', 'LS': 'Maseru', 'CG': 'Brazzaville', 'CF': 'Bangui', 'GA': 'Libreville',
    'BJ': 'Porto-Novo', 'TG': 'Lome', 'NE': 'Niamey', 'ML': 'Bamako', 'SN': 'Dakar',
    'GM': 'Banjul', 'GW': 'Bissau', 'SL': 'Freetown', 'LR': 'Monrovia', 'NG': 'Abuja',
    'MG': 'Antananarivo', 'MZ': 'Maputo', 'ZW': 'Harare', 'ZM': 'Lusaka', 'MW': 'Lilongwe',
    'TZ': 'Dodoma', 'KE': 'Nairobi', 'UG': 'Kampala', 'RW': 'Kigali', 'BI': 'Gitega',
    'ER': 'Asmara', 'AO': 'Luanda', 'BW': 'Gaborone', 'GL': 'Nuuk', 'HT': 'Port-au-Prince',
    'DO': 'Santo Domingo', 'CU': 'Havana', 'JM': 'Kingston', 'CR': 'San José', 'SV': 'San Salvador',
    'HN': 'Tegucigalpa', 'NI': 'Managua', 'BZ': 'Belmopan', 'TT': 'Port of Spain',
    'IS': 'Reykjavik', 'IE': 'Dublin', 'EE': 'Tallinn', 'LV': 'Riga', 'LT': 'Vilnius',
    'BY': 'Minsk', 'SI': 'Ljubljana', 'HR': 'Zagreb', 'SK': 'Bratislava', 'ME': 'Podgorica',
    'MT': 'Valletta', 'AD': 'Andorra la Vella', 'LI': 'Vaduz', 'FI': 'Helsinki', 'SE': 'Stockholm',
    'NO': 'Oslo', 'ES': 'Madrid', 'FR': 'Paris', 'DE': 'Berlin', 'TR': 'Ankara',
    'JP': 'Tokyo', 'LK': 'Kolombo', 'CA': 'Ottawa', 'AU': 'Canberra', 'NZ': 'Wellington',
    'AR': 'Buenos Aires', 'CL': 'Santiago', 'PE': 'Lima', 'UY': 'Montevideo', 'GY': 'Georgetown',
    'SR': 'Paramaribo', 'MA': 'Rabat', 'TL': 'Dili', 'PG': 'Port Moresby', 'FJ': 'Suva',
}

CAPITAL_NOTE = {
    'BO': 'Hükümet merkezi La Paz şehridir.',
    'ZA': 'Güney Afrika\'nın üç başkenti vardır: Pretoria, Cape Town ve Bloemfontein.',
    'NL': 'Hükümet Lahey şehrinde çalışır.',
    'IL': 'Kudüs\'ün başkent olması uluslararası alanda tartışmalıdır.',
    'CI': 'En büyük şehri ve eski başkenti Abidjan\'dır.',
    'NG': 'Eski başkenti ve en büyük şehri Lagos\'tur.',
    'TR': 'Ankara, 13 Ekim 1923\'te başkent oldu.',
    'KZ': 'Başkent 1997\'de Almatı\'dan Astana\'ya taşındı.',
    'BR': 'Brasilia, başkent olmak için sıfırdan planlanarak kuruldu.',
}

# Türkçe ad düzeltmeleri
NAME_TR = {
    'WS': 'Samoa', 'CL': 'Şili', 'CN': 'Çin', 'CZ': 'Çekya', 'JO': 'Ürdün', 'UZ': 'Özbekistan',
    'TD': 'Çad', 'US': 'Amerika Birleşik Devletleri', 'CV': 'Yeşil Burun Adaları',
    'CD': 'Kongo Demokratik Cumhuriyeti', 'SZ': 'Esvatini', 'VA': 'Vatikan',
}
SHORT_TR = {'US': 'ABD', 'GB': 'Birleşik Krallık', 'CD': 'Kongo DC', 'CG': 'Kongo',
            'AE': 'BAE', 'CF': 'Orta Afrika Cum.', 'DO': 'Dominik Cum.', 'BA': 'Bosna-Hersek',
            'VC': 'St. Vincent', 'KN': 'St. Kitts', 'ST': 'São Tomé', 'AG': 'Antigua'}

LANG_TR = {
    'English': 'İngilizce', 'French': 'Fransızca', 'Spanish': 'İspanyolca', 'Portuguese': 'Portekizce',
    'Arabic': 'Arapça', 'German': 'Almanca', 'Italian': 'İtalyanca', 'Russian': 'Rusça',
    'Chinese': 'Çince', 'Japanese': 'Japonca', 'Korean': 'Korece', 'Turkish': 'Türkçe',
    'Persian (Farsi)': 'Farsça', 'Hindi': 'Hintçe', 'Bengali': 'Bengalce', 'Urdu': 'Urduca',
    'Greek': 'Yunanca', 'Dutch': 'Felemenkçe', 'Swedish': 'İsveççe', 'Norwegian Bokmål': 'Norveççe',
    'Danish': 'Danca', 'Finnish': 'Fince', 'Polish': 'Lehçe', 'Czech': 'Çekçe', 'Slovak': 'Slovakça',
    'Hungarian': 'Macarca', 'Romanian': 'Rumence', 'Moldavian': 'Rumence', 'Bulgarian': 'Bulgarca',
    'Serbian': 'Sırpça', 'Croatian': 'Hırvatça', 'Bosnian': 'Boşnakça', 'Albanian': 'Arnavutça',
    'Ukrainian': 'Ukraynaca', 'Belarusian': 'Belarusça', 'Georgian': 'Gürcüce', 'Armenian': 'Ermenice',
    'Azerbaijani': 'Azerbaycan Türkçesi', 'Kazakh': 'Kazakça', 'Uzbek': 'Özbekçe', 'Turkmen': 'Türkmence',
    'Kyrgyz': 'Kırgızca', 'Tajik': 'Tacikçe', 'Mongolian': 'Moğolca', 'Hebrew': 'İbranice',
    'Swahili': 'Svahili', 'Amharic': 'Amharca', 'Indonesian': 'Endonezce', 'Malay': 'Malayca',
    'Thai': 'Tayca', 'Vietnamese': 'Vietnamca', 'Filipino': 'Filipince', 'Khmer': 'Khmerce',
    'Lao': 'Laoca', 'Burmese': 'Birmanca', 'Nepali': 'Nepalce', 'Tamil': 'Tamilce', 'Sinhala': 'Seylanca',
    'Icelandic': 'İzlandaca', 'Irish': 'İrlandaca', 'Estonian': 'Estonca', 'Latvian': 'Letonca',
    'Lithuanian': 'Litvanca', 'Slovene': 'Slovence', 'Macedonian': 'Makedonca', 'Maltese': 'Maltaca',
    'Latin': 'Latince', 'Luxembourgish': 'Lüksemburgca', 'Catalan': 'Katalanca', 'Somali': 'Somalice',
    'Pashto': 'Peştuca', 'Dari': 'Darice', 'Montenegrin': 'Karadağca', 'Māori': 'Maorice',
    'Zulu': 'Zuluca', 'Afrikaans': 'Afrikanca', 'Guaraní': 'Guarani dili', 'Quechua': 'Keçua dili',
    'Aymara': 'Aymara dili', 'Malagasy': 'Malgaşça', 'Kinyarwanda': 'Ruandaca', 'Berber': 'Berberice',
    'Haitian Creole': 'Haiti Kreolcesi', 'Samoan': 'Samoaca', 'Tongan': 'Tongaca', 'Fijian': 'Fiji dili',
    'Greenlandic': 'Grönlandca', 'Dzongkha': 'Dzongka', 'Tigrinya': 'Tigrinya dili', 'Maldivian': 'Divehi dili',
    'Kirundi': 'Kirundi dili', 'Sorani': 'Kürtçe', 'Romansh': 'Romanşça', 'Swiss German': 'Almanca',
    'Tetum': 'Tetum dili', 'Tok Pisin': 'Tok Pisin', 'Shona': 'Şona dili', 'Xhosa': 'Kosa dili',
    'Lingala': 'Lingala dili', 'Sango': 'Sango dili', 'Chewa': 'Çeva dili', 'Tswana': 'Setsvana',
    'Sotho': 'Sotho dili', 'Southern Sotho': 'Sotho dili', 'Swazi': 'Svati dili',
}

# Para birimi: ISO kodu -> Türkçe ad
CURRENCY_TR = {
    'TRY': 'Türk Lirası', 'EUR': 'Avro (Euro)', 'USD': 'Amerikan Doları', 'GBP': 'İngiliz Sterlini',
    'JPY': 'Japon Yeni', 'CNY': 'Çin Yuanı', 'RUB': 'Rus Rublesi', 'CHF': 'İsviçre Frangı',
    'XOF': 'Batı Afrika CFA Frangı', 'XAF': 'Orta Afrika CFA Frangı', 'XCD': 'Doğu Karayip Doları',
    'INR': 'Hint Rupisi', 'BRL': 'Brezilya Reali', 'ZAR': 'Güney Afrika Randı', 'KRW': 'Güney Kore Wonu',
    'AZN': 'Azerbaycan Manatı', 'TMT': 'Türkmen Manatı', 'SAR': 'Suudi Riyali', 'AED': 'BAE Dirhemi',
    'MAD': 'Fas Dirhemi', 'EGP': 'Mısır Lirası', 'KZT': 'Kazak Tengesi', 'UZS': 'Özbek Somu',
    'KGS': 'Kırgız Somu', 'GEL': 'Gürcü Larisi', 'MKD': 'Makedon Dinarı', 'SEK': 'İsveç Kronu',
    'NOK': 'Norveç Kronu', 'DKK': 'Danimarka Kronu', 'ISK': 'İzlanda Kronu', 'PLN': 'Polonya Zlotisi',
    'HUF': 'Macar Forinti', 'CZK': 'Çek Korunası', 'RON': 'Rumen Leyi', 'BGN': 'Bulgar Levası',
    'UAH': 'Ukrayna Grivnası', 'ILS': 'İsrail Şekeli', 'IDR': 'Endonezya Rupisi', 'THB': 'Tayland Bahtı',
    'VND': 'Vietnam Dongu', 'MXN': 'Meksika Pesosu', 'ARS': 'Arjantin Pesosu', 'CAD': 'Kanada Doları',
    'AUD': 'Avustralya Doları', 'NZD': 'Yeni Zelanda Doları', 'MNT': 'Moğol Tugriki', 'PEN': 'Peru Solü',
}
CURRENCY_UNIT_TR = [
    ('dollar', 'Doları'), ('peso', 'Pesosu'), ('franc', 'Frangı'), ('pound', 'Lirası'),
    ('dinar', 'Dinarı'), ('rupee', 'Rupisi'), ('shilling', 'Şilini'), ('krona', 'Kronu'),
    ('krone', 'Kronu'), ('ruble', 'Rublesi'), ('riyal', 'Riyali'), ('rial', 'Riyali'),
    ('won', 'Wonu'), ('dirham', 'Dirhemi'), ('lira', 'Lirası'), ('manat', 'Manatı'),
]

# Zorluk seviyeleri
EASY = set('TR US CA MX BR AR GB FR DE IT ES PT GR NL RU CN JP IN AU EG ZA SA IR IQ AZ KR SE NO FI PL UA CH AT BE DK IE NZ KE NG MA CO PE CL ID TH KZ PK SY BG GE CU'.split())
MEDIUM = EASY | set('HU CZ RO RS HR BA AL MK CY IS SK SI UZ TM KG AF MN VN PH MY SG BD NP LK KP IL JO LB AE QA KW OM YE VE EC BO PY UY DZ TN LY SD ET TZ GH SN CM CD AO MG SO JM PA CR GT FJ PG BY LT LV EE MD AM TJ MM KH LA NA ZW ZM CI ML NE TD LU MT ME HT DO'.split())
# Oyunlarda sorulmayanlar (tartışmalı / ülke olmayan)
NO_QUIZ = set('TW EH GL PS XK IL'.split())

FACTS = {
    'TR': 'Türkiye iki kıtada yer alır: toprakların çoğu Asya\'da (Anadolu), bir kısmı Avrupa\'dadır (Trakya). İstanbul iki kıtaya yayılan bir şehirdir!',
    'US': 'ABD\'nin 50 eyaleti vardır; bayrağındaki 50 yıldız bu eyaletleri temsil eder.',
    'CA': 'Kanada, Rusya\'dan sonra dünyanın en büyük ikinci ülkesidir ve dünyanın en uzun kıyı şeridine sahiptir.',
    'MX': 'Çikolatanın ana maddesi kakao ilk olarak Meksika ve çevresinde kullanılmıştır.',
    'BR': 'Dünyanın en büyük yağmur ormanı Amazon\'un büyük bölümü Brezilya\'dadır. Brezilya futbolda 5 kez dünya şampiyonu olmuştur.',
    'AR': 'Güney Amerika\'nın en yüksek dağı Aconcagua Arjantin\'dedir. Tango dansı da buradan çıkmıştır.',
    'GB': 'Birleşik Krallık; İngiltere, İskoçya, Galler ve Kuzey İrlanda\'dan oluşur. Londra\'daki ünlü saat kulesine Big Ben denir.',
    'FR': 'Eyfel Kulesi Paris\'tedir. Fransa, dünyada en çok turist ağırlayan ülkelerden biridir.',
    'DE': 'Almanya\'da 20.000\'den fazla şato ve kale vardır. Otomobil ilk kez Almanya\'da icat edildi.',
    'IT': 'İtalya haritada bir çizmeye benzer! Pizza ve makarna İtalya\'nın meşhur yemekleridir.',
    'ES': 'İspanya\'da her yıl domates savaşı festivali (La Tomatina) yapılır.',
    'PT': 'Portekizli denizci Vasco da Gama, Avrupa\'dan Hindistan\'a deniz yolunu bulan ilk kişidir.',
    'GR': 'Olimpiyat oyunları ilk kez Antik Yunanistan\'da yapıldı. Yunanistan\'da 6.000\'den fazla ada vardır.',
    'NL': 'Hollanda\'nın yaklaşık üçte biri deniz seviyesinin altındadır. Yel değirmenleri ve lalelerle ünlüdür.',
    'RU': 'Rusya dünyanın en büyük ülkesidir; hem Avrupa\'da hem Asya\'dadır ve 11 saat dilimine yayılır.',
    'CN': 'Çin Seddi dünyanın en uzun duvarıdır. Kâğıt, pusula ve barut Çin\'de icat edildi.',
    'JP': 'Japonya yaklaşık 14.000 adadan oluşur. Buna "Doğan Güneş Ülkesi" de denir.',
    'IN': 'Hindistan dünyanın en kalabalık ülkesidir. Satranç oyununun ilk hali Hindistan\'da ortaya çıktı.',
    'AU': 'Avustralya hem bir ülke hem de bir kıtadır. Kangurular ve koalalar burada yaşar.',
    'EG': 'Giza Piramitleri yaklaşık 4.500 yıllıktır. Nil Nehri Mısır\'ın can damarıdır.',
    'ZA': 'Güney Afrika\'nın üç başkenti vardır. Afrika\'nın en güney ucundaki Ümit Burnu buradadır.',
    'SA': 'Suudi Arabistan\'da hiç sürekli akan nehir yoktur. Kutsal şehirler Mekke ve Medine buradadır.',
    'IR': 'İran\'ın eski adı Pers\'tir. İran halıları dünyaca ünlüdür.',
    'IQ': 'Fırat ve Dicle nehirleri Irak\'tan geçer. Yazı ilk kez bu bölgede, Mezopotamya\'da icat edildi.',
    'AZ': 'Azerbaycan\'a "Ateşler Ülkesi" denir. Hazar Denizi kıyısındadır ve Türkçe\'ye çok yakın bir dil konuşulur.',
    'KR': 'Güney Kore teknolojide çok ileridir. Tekvando sporu Kore\'den çıkmıştır.',
    'SE': 'İsveç\'te yaz aylarında güneş neredeyse hiç batmaz. Nobel Ödülü\'nün kurucusu Alfred Nobel İsveçlidir.',
    'NO': 'Norveç\'in kıyılarında "fiyort" denen derin koylar vardır. Kuzey ışıkları burada görülebilir.',
    'FI': 'Finlandiya\'ya "Bin Göller Ülkesi" denir; aslında 180.000\'den fazla gölü vardır!',
    'PL': 'Ünlü bilim insanı Marie Curie ve gökbilimci Kopernik Polonyalıdır.',
    'UA': 'Ukrayna Avrupa\'nın (Rusya\'dan sonra) en büyük ikinci ülkesidir. Verimli toprakları nedeniyle "Avrupa\'nın ekmek sepeti" denir.',
    'CH': 'İsviçre saatleri ve çikolatasıyla ünlüdür. Alp Dağları ülkenin büyük bölümünü kaplar.',
    'AT': 'Ünlü besteci Mozart Avusturya\'nın Salzburg şehrinde doğdu.',
    'BE': 'Belçika çikolata ve waffle ile ünlüdür. Avrupa Birliği\'nin merkezi Brüksel\'dedir.',
    'DK': 'LEGO oyuncakları Danimarka\'da icat edildi. Grönland de Danimarka Krallığı\'na bağlıdır.',
    'IE': 'İrlanda\'ya çok yeşil olduğu için "Zümrüt Ada" denir.',
    'NZ': 'Yeni Zelanda\'da insandan çok koyun vardır! Kivi kuşu ülkenin simgesidir.',
    'KE': 'Kenya\'daki safari parklarında aslan, fil ve zürafa görülebilir. Ekvator çizgisi Kenya\'dan geçer.',
    'NG': 'Nijerya Afrika\'nın en kalabalık ülkesidir.',
    'MA': 'Fas, Cebelitarık Boğazı ile Avrupa\'ya sadece 14 km uzaklıktadır.',
    'CO': 'Kolombiya, dünyada en çok kuş türüne ev sahipliği yapan ülkedir.',
    'PE': 'İnkaların antik şehri Machu Picchu Peru\'dadır.',
    'CL': 'Şili dünyanın en uzun ve en ince ülkesidir; kuzeyindeki Atacama Çölü dünyanın en kurak yerlerinden biridir.',
    'ID': 'Endonezya 17.000\'den fazla adadan oluşan dünyanın en büyük ada ülkesidir.',
    'TH': 'Tayland\'ın simgesi fildir. Eski adı Siyam\'dır.',
    'KZ': 'Kazakistan dünyanın denize kıyısı olmayan en büyük ülkesidir. İlk uzay yolculukları Baykonur\'dan yapıldı.',
    'PK': 'Dünyanın en yüksek ikinci dağı K2, Pakistan\'dadır.',
    'SY': 'Başkent Şam, dünyanın sürekli yerleşim gören en eski şehirlerinden biridir.',
    'BG': 'Bulgaristan gül yağı üretimiyle ünlüdür.',
    'GE': 'Gürcistan\'ın kendine özgü bir alfabesi vardır. Kafkas Dağları\'nın eteklerindedir.',
    'CU': 'Küba, Karayip Denizi\'nin en büyük adasıdır.',
    'HU': 'Rubik küpü Macar mimar Ernő Rubik tarafından icat edildi.',
    'CZ': 'Prag\'daki astronomik saat 600 yıldan daha eskidir ve hâlâ çalışır.',
    'RO': 'Karpat Dağları Romanya\'dadır. Tuna Nehri Karadeniz\'e burada dökülür.',
    'RS': 'Tuna ve Sava nehirleri başkent Belgrad\'da birleşir.',
    'HR': 'Kravat Hırvatistan\'dan dünyaya yayılmıştır! Adriyatik kıyısında 1.000\'den fazla ada vardır.',
    'BA': 'Mostar Köprüsü Osmanlı döneminde Mimar Hayreddin tarafından yapıldı.',
    'AL': 'Arnavutluk\'un bayrağında çift başlı bir kartal vardır.',
    'MK': 'Ohri Gölü dünyanın en eski göllerinden biridir.',
    'CY': 'Kıbrıs, Akdeniz\'in üçüncü büyük adasıdır.',
    'IS': 'İzlanda\'da yanardağlar ve buzullar yan yanadır. Sıcak su fışkıran gayzerler buradadır.',
    'SK': 'Slovakya\'da 6.000\'den fazla mağara vardır.',
    'SI': 'Slovenya\'nın yarıdan fazlası ormanlarla kaplıdır.',
    'UZ': 'Semerkant ve Buhara gibi tarihi İpek Yolu şehirleri Özbekistan\'dadır.',
    'TM': 'Türkmenistan\'daki Karakum Çölü\'nde yıllardır yanan "Cehennem Kapısı" adlı bir krater vardır.',
    'KG': 'Kırgızistan\'ın %90\'ından fazlası dağlıktır. Manas Destanı dünyanın en uzun destanlarındandır.',
    'AF': 'Afganistan\'ın denize kıyısı yoktur ve Hindukuş Dağları ülkeyi ortadan böler.',
    'MN': 'Moğolistan\'da insanların bir kısmı hâlâ "ger" denen çadırlarda göçebe yaşar. Gobi Çölü buradadır.',
    'VN': 'Vietnam\'ın haritadaki şekli "S" harfine benzer.',
    'PH': 'Filipinler 7.000\'den fazla adadan oluşur.',
    'MY': 'Kuala Lumpur\'daki Petronas İkiz Kuleleri bir zamanlar dünyanın en yüksek binalarıydı.',
    'SG': 'Singapur hem bir şehir hem de bir ülkedir.',
    'BD': 'Bangladeş dünyanın en kalabalık ülkelerindendir. Dünyanın en büyük deltası buradadır.',
    'NP': 'Dünyanın en yüksek dağı Everest Nepal ile Çin sınırındadır. Nepal bayrağı dikdörtgen olmayan tek bayraktır!',
    'LK': 'Sri Lanka Hindistan\'ın güneyinde bir adadır ve çay üretimiyle ünlüdür.',
    'KP': 'Kuzey Kore dış dünyaya en kapalı ülkelerden biridir.',
    'IL': 'Lut Gölü (Ölü Deniz) dünyanın karadaki en alçak noktasıdır; suyu o kadar tuzludur ki insanlar batmadan yüzebilir.',
    'JO': 'Kayalara oyulmuş antik şehir Petra Ürdün\'dedir.',
    'LB': 'Lübnan bayrağında sedir ağacı vardır.',
    'AE': 'Dünyanın en yüksek binası Burj Halife, Dubai\'dedir.',
    'QA': 'Katar, 2022 FIFA Dünya Kupası\'na ev sahipliği yaptı.',
    'KW': 'Kuveyt küçük ama petrol açısından çok zengin bir ülkedir.',
    'OM': 'Umman, Arap Yarımadası\'nın en eski bağımsız ülkelerinden biridir.',
    'YE': 'Yemen\'deki Sana şehrinde yüzlerce yıllık çamur tuğladan "gökdelenler" vardır.',
    'VE': 'Dünyanın en yüksek şelalesi Angel Şelalesi Venezuela\'dadır.',
    'EC': 'Ekvador adını üzerinden geçen Ekvator çizgisinden alır. Galapagos Adaları da buradadır.',
    'BO': 'Bolivya\'daki Uyuni Tuz Düzlüğü dünyanın en büyük tuz çölüdür.',
    'PY': 'Paraguay\'da halkın çoğu hem İspanyolca hem Guarani dilini konuşur.',
    'UY': 'İlk FIFA Dünya Kupası 1930\'da Uruguay\'da yapıldı ve Uruguay kazandı.',
    'DZ': 'Cezayir Afrika\'nın yüzölçümü en büyük ülkesidir. Topraklarının çoğu Sahra Çölü\'dür.',
    'TN': 'Tunus, Afrika\'nın en kuzeydeki ülkesidir.',
    'LY': 'Libya\'nın %90\'ından fazlası çöldür.',
    'SD': 'Sudan\'da Mısır\'dakinden daha fazla piramit vardır!',
    'ET': 'Kahvenin anavatanı Etiyopya\'dır.',
    'TZ': 'Afrika\'nın en yüksek dağı Kilimanjaro Tanzanya\'dadır.',
    'GH': 'Gana dünyanın en çok kakao üreten ülkelerindendir.',
    'SN': 'Senegal, Afrika kıtasının en batısındaki ülkedir.',
    'CM': 'Kamerun\'a çok farklı doğal güzellikleri olduğu için "Minyatür Afrika" denir.',
    'CD': 'Kongo Nehri dünyanın en derin nehridir ve bu ülkeden geçer.',
    'AO': 'Angola\'nın resmi dili Portekizcedir.',
    'MG': 'Madagaskar\'daki hayvanların çoğu (örneğin lemurlar) dünyanın başka hiçbir yerinde yaşamaz.',
    'SO': 'Somali, Afrika\'nın en uzun kıyı şeridine sahip ülkesidir.',
    'JM': 'Dünyanın en hızlı koşucularından Usain Bolt Jamaikalıdır.',
    'PA': 'Panama Kanalı Atlas ve Büyük Okyanus\'u birbirine bağlar.',
    'CR': 'Kosta Rika\'nın ordusu yoktur ve ormanları çok zengindir.',
    'GT': 'Guatemala\'da eski Maya uygarlığının şehirleri bulunur.',
    'FJ': 'Fiji 300\'den fazla adadan oluşur.',
    'PG': 'Papua Yeni Gine\'de 800\'den fazla dil konuşulur!',
    'BY': 'Belarus\'un denize kıyısı yoktur ve çok sayıda gölü vardır.',
    'LT': 'Litvanya\'nın sahilinde kum tepeleriyle ünlü Kür Kıstağı vardır.',
    'LV': 'Letonya\'nın yarısı ormanlarla kaplıdır.',
    'EE': 'Estonya\'da çevrim içi oy vermek mümkündür; Skype burada geliştirildi.',
    'MD': 'Moldova\'nın denize kıyısı yoktur; Gagavuz Türkleri bu ülkede yaşar.',
    'AM': 'Ağrı Dağı Ermenistan\'dan da görülebilir.',
    'TJ': 'Tacikistan\'ın %90\'ından fazlası dağlıktır; Pamir Dağları\'na "Dünyanın Çatısı" denir.',
    'MM': 'Myanmar binlerce altın kubbeli pagodasıyla ünlüdür.',
    'KH': 'Dünyanın en büyük dini yapısı Angkor Wat, Kamboçya\'dadır ve bayrağında yer alır.',
    'LA': 'Laos, Güneydoğu Asya\'nın denize kıyısı olmayan tek ülkesidir.',
    'NA': 'Namibya\'daki Namib Çölü dünyanın en eski çölü sayılır.',
    'ZW': 'Dev Victoria Şelalesi Zimbabve ile Zambiya sınırındadır.',
    'ZM': 'Zambiya adını Zambezi Nehri\'nden alır.',
    'CI': 'Fildişi Sahili dünyanın en çok kakao üreten ülkesidir.',
    'ML': 'Mali\'deki Timbuktu şehri eskiden önemli bir bilim ve ticaret merkeziydi.',
    'NE': 'Nijer adını Nijer Nehri\'nden alır ve topraklarının çoğu Sahra Çölü\'dür.',
    'TD': 'Çad adını Çad Gölü\'nden alır.',
    'LU': 'Lüksemburg dünyanın en zengin ülkelerinden biridir.',
    'MT': 'Malta\'da piramitlerden bile eski taş tapınaklar vardır.',
    'ME': 'Karadağ adını ülkedeki koyu renkli ormanlık dağlardan alır.',
    'HT': 'Haiti, köleliği kaldırarak bağımsızlığını kazanan ilk ülkedir (1804).',
    'DO': 'Dominik Cumhuriyeti, Hispaniola adasını Haiti ile paylaşır.',
    'VA': 'Vatikan dünyanın en küçük ülkesidir; Roma şehrinin içindedir!',
    'MC': 'Monako dünyanın en küçük ikinci ülkesidir ve Formula 1 yarışıyla ünlüdür.',
    'SM': 'San Marino dünyanın en eski cumhuriyetlerinden biridir.',
    'LI': 'Lihtenştayn, İsviçre ile Avusturya arasında küçük bir dağ ülkesidir.',
    'AD': 'Andorra, Pireneler\'de Fransa ile İspanya arasında küçük bir ülkedir.',
    'MV': 'Maldivler dünyanın en alçak ülkesidir; ortalama yüksekliği 1,5 metredir.',
    'BT': 'Butan\'da mutluluk ölçülür; ülke "Gayri Safi Milli Mutluluk" ile ünlüdür.',
    'TW': 'Tayvan, Çin\'in güneydoğusunda bir adadır.',
    'GL': 'Grönland dünyanın en büyük adasıdır ve büyük kısmı buzla kaplıdır. Danimarka\'ya bağlıdır.',
    'SS': 'Güney Sudan dünyanın en genç ülkesidir (2011).',
    'RW': 'Ruanda\'ya "Bin Tepeler Ülkesi" denir; dağ gorilleri burada yaşar.',
    'UG': 'Afrika\'nın en büyük gölü Victoria Gölü\'nün bir kısmı Uganda\'dadır.',
    'BW': 'Botsvana\'daki Okavango Deltası denize dökülmeyen, çölde kaybolan bir nehir deltasıdır.',
    'MZ': 'Mozambik bayrağında bir tüfek vardır.',
    'MW': 'Malavi Gölü\'nde dünyada en çok balık türü bulunan göllerden biridir.',
    'ER': 'Eritre, Kızıldeniz kıyısında yer alır.',
    'DJ': 'Cibuti\'deki Assal Gölü, Afrika\'nın en alçak noktasıdır.',
    'MR': 'Moritanya\'daki "Sahra\'nın Gözü" uzaydan görülebilen dev bir halka şeklidir.',
    'GA': 'Gabon\'un yaklaşık %85\'i yağmur ormanlarıyla kaplıdır.',
    'NI': 'Nikaragua, Orta Amerika\'nın en büyük ülkesidir; göllerinde tatlı su köpekbalıkları yaşar.',
    'HN': 'Honduras\'ta eski Maya şehri Copán bulunur.',
    'SV': 'El Salvador Orta Amerika\'nın en küçük ülkesidir ve "Yanardağlar Ülkesi" olarak bilinir.',
    'BS': 'Bahamalar 700\'den fazla adadan oluşur.',
    'TT': 'Steel drum (çelik davul) çalgısı Trinidad ve Tobago\'da icat edildi.',
    'GY': 'Guyana, Güney Amerika\'da resmi dili İngilizce olan tek ülkedir.',
    'SR': 'Surinam Güney Amerika\'nın en küçük ülkesidir.',
    'IS_': '',
}

# ---- Coğrafi noktalar ----
# kind: peak | range | desert | landmark | city | sea | ocean | strait | lake | river
PEAKS = [
    ('everest', 'Everest Dağı', 27.988, 86.925, 'Dünyanın en yüksek dağıdır: 8.849 metre! Nepal ile Çin sınırındadır, Himalayalar\'dadır.', 'NP'),
    ('k2', 'K2 Dağı', 35.88, 76.515, 'Dünyanın en yüksek ikinci dağıdır (8.611 m). Pakistan ile Çin sınırındadır.', 'PK'),
    ('kilimanjaro', 'Kilimanjaro Dağı', -3.067, 37.355, 'Afrika\'nın en yüksek dağıdır (5.895 m). Ekvatora yakın olmasına rağmen tepesi karlıdır.', 'TZ'),
    ('aconcagua', 'Aconcagua Dağı', -32.653, -70.011, 'Güney Amerika\'nın ve And Dağları\'nın en yüksek zirvesidir (6.961 m).', 'AR'),
    ('denali', 'Denali Dağı', 63.069, -151.007, 'Kuzey Amerika\'nın en yüksek dağıdır (6.190 m). ABD\'nin Alaska eyaletindedir.', 'US'),
    ('elbrus', 'Elbruz Dağı', 43.355, 42.439, 'Avrupa\'nın en yüksek dağı kabul edilir (5.642 m). Kafkas Dağları\'ndadır.', 'RU'),
    ('montblanc', 'Mont Blanc', 45.833, 6.865, 'Alpler\'in en yüksek dağıdır (4.806 m). Adı "Beyaz Dağ" demektir.', 'FR'),
    ('agri', 'Ağrı Dağı', 39.702, 44.298, 'Türkiye\'nin en yüksek dağıdır (5.137 m). Sönmüş bir yanardağdır.', 'TR'),
    ('erciyes', 'Erciyes Dağı', 38.531, 35.447, 'İç Anadolu\'nun en yüksek dağıdır (3.917 m). Kayseri\'dedir ve kayak merkezi vardır.', 'TR'),
    ('uludag', 'Uludağ', 40.07, 29.22, 'Bursa\'daki Uludağ (2.543 m) Türkiye\'nin en ünlü kayak merkezlerindendir. Eski adı Keşiş Dağı\'dır.', 'TR'),
    ('kackar', 'Kaçkar Dağı', 40.834, 41.161, 'Doğu Karadeniz Dağları\'nın en yüksek zirvesidir (3.937 m).', 'TR'),
    ('fuji', 'Fuji Dağı', 35.361, 138.728, 'Japonya\'nın en yüksek dağı ve sembolüdür (3.776 m). Bir yanardağdır.', 'JP'),
    ('matterhorn', 'Matterhorn', 45.976, 7.658, 'Piramit şeklindeki bu ünlü Alp dağı İsviçre ile İtalya sınırındadır (4.478 m).', 'CH'),
    ('etna', 'Etna Yanardağı', 37.751, 14.993, 'Avrupa\'nın en aktif yanardağıdır. İtalya\'nın Sicilya adasındadır.', 'IT'),
    ('vezuv', 'Vezüv Yanardağı', 40.821, 14.426, 'Yaklaşık 2.000 yıl önce patlayarak Pompeii şehrini küllerin altında bırakmıştır.', 'IT'),
    ('olimpos', 'Olimpos Dağı', 40.086, 22.358, 'Yunanistan\'ın en yüksek dağıdır. Eski Yunan efsanelerinde tanrıların evi sayılırdı.', 'GR'),
    ('maunakea', 'Mauna Kea', 19.821, -155.468, 'Hawaii\'deki bu dağ, deniz tabanından ölçülürse Everest\'ten daha uzundur!', 'US'),
    ('vinson', 'Vinson Dağı', -78.525, -85.617, 'Antarktika\'nın en yüksek dağıdır (4.892 m).', None),
    ('kosciuszko', 'Kosciuszko Dağı', -36.456, 148.263, 'Avustralya\'nın en yüksek dağıdır (2.228 m).', 'AU'),
    ('hasan', 'Hasan Dağı', 38.127, 34.167, 'Aksaray\'daki bu yanardağın 9.000 yıl önceki patlaması bir duvar resminde çizilmiş olabilir.', 'TR'),
]

RANGES = [
    ('himalaya', 'Himalaya Dağları', [[73, 35.5], [77, 33], [81, 30], [85, 28], [88, 27.8], [92, 27.8], [95, 28.8]], 'Dünyanın en yüksek dağ sırasıdır. Everest dahil 8.000 metreyi aşan dağların hepsi bu bölgededir.'),
    ('and', 'And Dağları', [[-72, 10], [-77, 3], [-78.5, -2], [-76, -10], [-70, -17], [-68.5, -24], [-70, -33], [-71.5, -41], [-73, -50], [-72, -54]], 'Dünyanın en uzun dağ sırasıdır (yaklaşık 7.000 km). Güney Amerika\'nın batısı boyunca uzanır.'),
    ('alpler', 'Alp Dağları', [[6, 44], [7, 45.8], [9, 46.4], [11, 47], [13.5, 47.2], [15.5, 47.5]], 'Avrupa\'nın en önemli dağ sırasıdır. Fransa, İsviçre, İtalya ve Avusturya\'dan geçer.'),
    ('kayalik', 'Kayalık Dağlar', [[-106, 35], [-106, 39], [-110, 43], [-114, 47], [-117, 51], [-122, 55], [-126, 59]], 'Kuzey Amerika\'nın batısında, Kanada\'dan ABD\'ye uzanan büyük dağ sırasıdır.'),
    ('ural', 'Ural Dağları', [[59, 51.5], [58.5, 55], [59.5, 60], [60, 64], [62, 67], [65, 69]], 'Avrupa ile Asya kıtalarını birbirinden ayıran sınır sayılır.'),
    ('toros', 'Toros Dağları', [[29.5, 36.6], [31.5, 37], [33, 36.9], [35, 37.3], [36.5, 37.8], [38.5, 38.3]], 'Türkiye\'nin güneyinde, Akdeniz kıyısı boyunca uzanan dağlardır.'),
    ('kanadolu', 'Kuzey Anadolu Dağları', [[31, 41], [34, 41.2], [37, 40.7], [39.5, 40.6], [41.5, 41]], 'Karadeniz kıyısına paralel uzanır. Bu dağlar yüzünden Karadeniz\'de çok yağmur yağar.'),
    ('kafkas', 'Kafkas Dağları', [[37.5, 44.3], [40, 43.5], [43, 42.8], [45.5, 42], [48, 41.5], [49.5, 40.8]], 'Karadeniz ile Hazar Denizi arasında uzanır. En yüksek zirvesi Elbruz\'dur.'),
    ('atlas', 'Atlas Dağları', [[-9.5, 30.5], [-6, 31.5], [-3, 33], [0, 34], [3, 35], [7, 36], [10, 36.5]], 'Kuzeybatı Afrika\'da Fas, Cezayir ve Tunus\'tan geçer.'),
    ('apalas', 'Apalaş Dağları', [[-85, 34], [-82, 36], [-79.5, 38.5], [-76, 41], [-73, 43], [-70, 45], [-67, 47]], 'Kuzey Amerika\'nın doğusundaki çok eski dağlardır.'),
    ('pireneler', 'Pireneler', [[-1.8, 43.2], [0, 42.8], [1.5, 42.6], [3.1, 42.4]], 'Fransa ile İspanya arasında doğal bir sınır oluşturur.'),
    ('karpat', 'Karpat Dağları', [[18, 49.2], [21, 49.3], [23.5, 48.3], [25, 47.5], [26, 46], [25, 45.4], [22.5, 45.1]], 'Orta ve Doğu Avrupa\'da yay şeklinde uzanır; büyük kısmı Romanya\'dadır.'),
    ('bolme', 'Büyük Bölme Silsilesi', [[145.5, -15], [147, -20], [150, -25], [152, -29], [150, -33], [148, -36], [146, -37.5]], 'Avustralya\'nın doğu kıyısı boyunca uzanan en uzun dağ sırasıdır.'),
]

DESERTS = [
    ('sahra', 'Sahra Çölü', 23, 13, 'Dünyanın en büyük sıcak çölüdür; neredeyse ABD kadar büyüktür!'),
    ('gobi', 'Gobi Çölü', 43, 105, 'Moğolistan ve Çin\'dedir. Burada dinozor fosilleri bulunmuştur.'),
    ('arabistan', 'Arabistan Çölü', 22, 48, 'Arap Yarımadası\'nın büyük kısmını kaplar. Kum tepeleri 250 metreye ulaşabilir.'),
    ('atacama', 'Atacama Çölü', -24, -69.5, 'Dünyanın en kurak yerlerinden biridir; bazı bölgelerine yıllardır yağmur yağmamıştır.'),
    ('kalahari', 'Kalahari Çölü', -23, 22, 'Güney Afrika\'da, Botsvana ve Namibya\'dadır.'),
    ('buyukavustralya', 'Büyük Victoria Çölü', -29, 127, 'Avustralya\'nın en büyük çölüdür.'),
    ('karakum', 'Karakum Çölü', 39.5, 59.5, 'Türkmenistan\'ın büyük kısmını kaplayan "Kara Kum" demek olan çöldür.'),
]

SEAS = [
    ('pasifik', 'Büyük Okyanus (Pasifik)', 5, -150, 'ocean', 'Dünyanın en büyük ve en derin okyanusudur. Tüm karaların toplamından daha büyüktür!'),
    ('atlas_ok', 'Atlas Okyanusu', 20, -40, 'ocean', 'Dünyanın ikinci büyük okyanusudur. Avrupa ve Afrika\'yı Amerika\'dan ayırır.'),
    ('hint', 'Hint Okyanusu', -20, 78, 'ocean', 'Dünyanın üçüncü büyük okyanusudur. En sıcak okyanustur.'),
    ('arktik', 'Kuzey Buz Denizi', 80, 10, 'ocean', 'En küçük ve en soğuk okyanustur. Kutup ayıları buranın buzlarında yaşar.'),
    ('guney', 'Güney Okyanusu', -62, 30, 'ocean', 'Antarktika\'nın etrafını çevreleyen okyanustur. Penguenler burada yaşar.'),
    ('akdeniz', 'Akdeniz', 35, 18, 'sea', 'Avrupa, Asya ve Afrika arasında kalan denizdir. Türkiye\'nin güney kıyıları Akdeniz\'dedir.'),
    ('karadeniz', 'Karadeniz', 43.2, 34, 'sea', 'Türkiye\'nin kuzeyindeki denizdir. Tuna, Dinyeper gibi büyük nehirler buraya dökülür.'),
    ('ege', 'Ege Denizi', 38.8, 25.2, 'sea', 'Türkiye ile Yunanistan arasındadır ve çok sayıda adası vardır.'),
    ('marmara', 'Marmara Denizi', 40.72, 28.2, 'sea', 'Tamamen Türkiye topraklarında bulunan bir iç denizdir. Karadeniz ile Ege\'yi bağlar.'),
    ('kizildeniz', 'Kızıldeniz', 20, 38.5, 'sea', 'Afrika ile Arap Yarımadası arasındadır. Mercan resifleriyle ünlüdür.'),
    ('karayip', 'Karayip Denizi', 15, -75, 'sea', 'Orta Amerika\'nın doğusundaki sıcak, turkuaz renkli denizdir.'),
    ('kuzeydenizi', 'Kuzey Denizi', 56, 3, 'sea', 'Büyük Britanya ile Norveç, Danimarka ve Hollanda arasındadır.'),
    ('baltik', 'Baltık Denizi', 58, 20, 'sea', 'Kuzey Avrupa\'da, suyu az tuzlu bir denizdir.'),
    ('arap', 'Umman Denizi', 15, 64, 'sea', 'Hint Okyanusu\'nun Arap Yarımadası ile Hindistan arasındaki kuzey bölümüdür.'),
    ('gucin', 'Güney Çin Denizi', 13, 114, 'sea', 'Çin, Vietnam, Filipinler ve Malezya arasındadır.'),
    ('meksika', 'Meksika Körfezi', 25, -90, 'sea', 'ABD, Meksika ve Küba ile çevrili büyük bir körfezdir.'),
    ('basra', 'Basra Körfezi', 27, 51, 'sea', 'İran ile Arap Yarımadası arasındadır ve petrolüyle ünlüdür.'),
    ('japon', 'Japon Denizi', 40, 134, 'sea', 'Japonya ile Kore Yarımadası arasındadır.'),
]

STRAITS = [
    ('istanbulbogazi', 'İstanbul Boğazı', 41.12, 29.06, 'Karadeniz ile Marmara Denizi\'ni bağlar; Asya ile Avrupa\'yı ayırır.'),
    ('canakkale', 'Çanakkale Boğazı', 40.2, 26.4, 'Marmara Denizi ile Ege Denizi\'ni bağlar.'),
    ('cebelitarik', 'Cebelitarık Boğazı', 35.95, -5.6, 'Akdeniz\'i Atlas Okyanusu\'na bağlar; Avrupa ile Afrika\'yı ayırır.'),
    ('panama_k', 'Panama Kanalı', 9.1, -79.7, 'İnsan yapımı bu kanal gemilerin Atlas ve Büyük Okyanus arasında geçmesini sağlar.'),
    ('suveys', 'Süveyş Kanalı', 30.6, 32.34, 'Akdeniz ile Kızıldeniz\'i bağlayan kanaldır; gemiler Afrika\'yı dolaşmak zorunda kalmaz.'),
    ('bering', 'Bering Boğazı', 65.8, -169, 'Asya ile Kuzey Amerika\'yı ayırır; en dar yeri sadece 82 km\'dir.'),
]

LANDMARKS = [
    ('eyfel', 'Eyfel Kulesi', 48.858, 2.294, 'Paris\'teki bu demir kule 1889\'da yapıldı ve 330 metre yüksekliğindedir.', 'FR'),
    ('piramitler', 'Giza Piramitleri', 29.979, 31.134, 'Antik Dünyanın Yedi Harikası\'ndan bugüne kalan tek yapıdır.', 'EG'),
    ('cinseddi', 'Çin Seddi', 40.43, 116.57, 'Binlerce kilometre uzunluğundaki bu duvar Çin\'i korumak için yapıldı.', 'CN'),
    ('ozgurluk', 'Özgürlük Heykeli', 40.689, -74.045, 'New York\'taki bu heykel Fransa\'nın ABD\'ye hediyesidir.', 'US'),
    ('tacmahal', 'Tac Mahal', 27.175, 78.042, 'Hindistan\'daki bu beyaz mermer yapı bir hükümdarın eşi için yaptırıldı.', 'IN'),
    ('kolezyum', 'Kolezyum', 41.89, 12.492, 'Roma\'daki bu dev antik arenada yaklaşık 50.000 kişi otururdu.', 'IT'),
    ('machupicchu', 'Machu Picchu', -13.163, -72.545, 'And Dağları\'nın tepesinde kurulmuş antik İnka şehri.', 'PE'),
    ('sidneyopera', 'Sidney Opera Binası', -33.857, 151.215, 'Yelkenlere benzeyen çatısıyla Avustralya\'nın en ünlü binası.', 'AU'),
    ('kurtarici', 'Kurtarıcı İsa Heykeli', -22.952, -43.211, 'Rio de Janeiro\'da bir dağın tepesindeki dev heykel.', 'BR'),
    ('petra', 'Petra', 30.328, 35.444, 'Ürdün\'de pembe kayalara oyulmuş antik şehir.', 'JO'),
    ('ayasofya', 'Ayasofya', 41.0086, 28.98, 'İstanbul\'daki bu yapı yaklaşık 1.500 yıllıktır ve dev kubbesiyle ünlüdür.', 'TR'),
    ('kapadokya', 'Kapadokya', 38.64, 34.83, 'Peribacaları ve sıcak hava balonlarıyla ünlü, Nevşehir çevresindeki bölge.', 'TR'),
    ('pamukkale', 'Pamukkale', 37.92, 29.12, 'Denizli\'deki bembeyaz kireç taşı havuzları pamuktan bir kaleye benzer.', 'TR'),
    ('nemrut', 'Nemrut Dağı', 37.98, 38.74, 'Adıyaman\'da, tepesinde dev taş heykellerin bulunduğu dağ.', 'TR'),
    ('gobeklitepe', 'Göbeklitepe', 37.223, 38.922, 'Şanlıurfa\'daki yaklaşık 12.000 yıllık bu yer, bilinen en eski tapınaktır.', 'TR'),
    ('efes', 'Efes Antik Kenti', 37.94, 27.34, 'İzmir\'deki bu antik şehirde ünlü Celsus Kütüphanesi bulunur.', 'TR'),
    ('bigben', 'Big Ben', 51.5007, -0.1246, 'Londra\'daki ünlü saat kulesinin büyük çanının adıdır.', 'GB'),
    ('pisa', 'Pisa Kulesi', 43.723, 10.396, 'İtalya\'daki bu çan kulesi yumuşak zemin yüzünden eğiktir.', 'IT'),
    ('angkor', 'Angkor Wat', 13.412, 103.867, 'Kamboçya\'daki dünyanın en büyük dini yapısı.', 'KH'),
    ('chichenitza', 'Chichen Itza', 20.683, -88.569, 'Meksika\'daki basamaklı Maya piramidi.', 'MX'),
    ('stonehenge', 'Stonehenge', 51.179, -1.826, 'İngiltere\'de daire şeklinde dizilmiş 5.000 yıllık dev taşlar.', 'GB'),
    ('burj', 'Burj Halife', 25.197, 55.274, 'Dubai\'deki dünyanın en yüksek binası (828 m).', 'AE'),
    ('niagara', 'Niagara Şelalesi', 43.08, -79.07, 'ABD ile Kanada sınırındaki çok güçlü ve ünlü şelale.', 'US'),
    ('victoriaf', 'Victoria Şelalesi', -17.925, 25.857, 'Zambezi Nehri üzerindeki bu şelalenin yerel adı "Gürleyen Duman"dır.', 'ZW'),
    ('angel', 'Angel Şelalesi', 5.97, -62.535, 'Venezuela\'daki dünyanın en yüksek şelalesi (979 m).', 'VE'),
    ('kanyon', 'Büyük Kanyon', 36.1, -112.1, 'Colorado Nehri\'nin milyonlarca yılda oyduğu dev vadi (ABD).', 'US'),
    ('setresifi', 'Büyük Set Resifi', -18.3, 147.7, 'Avustralya kıyısındaki dünyanın en büyük mercan resifi; uzaydan görülebilir.', 'AU'),
    ('amazon_orman', 'Amazon Yağmur Ormanı', -4, -62, 'Dünyanın en büyük yağmur ormanıdır; "dünyanın akciğeri" olarak bilinir.', 'BR'),
    ('kuzeykutbu', 'Kuzey Kutbu', 89.5, 0, 'Dünyanın en kuzey noktası. Burada kara yoktur, sadece donmuş deniz vardır.', None),
    ('olu_deniz', 'Lut Gölü (Ölü Deniz)', 31.5, 35.5, 'Karadaki en alçak nokta (deniz seviyesinin 430 m altı). Suyunda batmadan yüzülür.', 'JO'),
]

CITIES = [
    ('istanbul', 'İstanbul', 41.01, 28.98, 'Türkiye\'nin en kalabalık şehri. İki kıtaya yayılır ve tarihte üç büyük imparatorluğa başkentlik yaptı.', 'TR'),
    ('izmir', 'İzmir', 38.42, 27.14, 'Türkiye\'nin üçüncü büyük şehri; Ege Denizi kıyısındadır.', 'TR'),
    ('antalya', 'Antalya', 36.9, 30.7, 'Akdeniz kıyısında, turizmin başkenti sayılan şehir.', 'TR'),
    ('bursa', 'Bursa', 40.19, 29.06, 'Osmanlı Devleti\'nin ilk başkentlerinden. İskender kebap ve Uludağ ile ünlü.', 'TR'),
    ('trabzon', 'Trabzon', 41.0, 39.72, 'Karadeniz kıyısında; Sümela Manastırı ve Uzungöl yakınındadır.', 'TR'),
    ('konya', 'Konya', 37.87, 32.48, 'Yüzölçümü en büyük ilimizdir. Mevlana burada yaşamıştır.', 'TR'),
    ('adana', 'Adana', 37.0, 35.32, 'Seyhan Nehri kıyısında, verimli Çukurova\'nın merkezi.', 'TR'),
    ('gaziantep', 'Gaziantep', 37.07, 37.38, 'Baklava ve fıstığıyla ünlü, mutfağıyla dünyaca tanınan şehir.', 'TR'),
    ('erzurum', 'Erzurum', 39.9, 41.27, 'Türkiye\'nin en soğuk şehirlerinden; Palandöken kayak merkezi buradadır.', 'TR'),
    ('van', 'Van', 38.5, 43.38, 'Türkiye\'nin en büyük gölü Van Gölü\'nün kıyısında. Van kedisi ile ünlü.', 'TR'),
    ('diyarbakir', 'Diyarbakır', 37.91, 40.23, 'Dicle Nehri kıyısında, dünyanın en uzun şehir surlarından birine sahip.', 'TR'),
    ('samsun', 'Samsun', 41.29, 36.33, 'Atatürk 19 Mayıs 1919\'da Kurtuluş Savaşı\'nı başlatmak için buraya çıktı.', 'TR'),
    ('eskisehir', 'Eskişehir', 39.78, 30.52, 'Porsuk Çayı kıyısında; üniversiteleri ve lületaşıyla ünlü öğrenci şehri.', 'TR'),
    ('kayseri', 'Kayseri', 38.73, 35.49, 'Erciyes Dağı\'nın eteğinde; mantısı, pastırması ve ticaretiyle ünlü.', 'TR'),
    ('mardin', 'Mardin', 37.31, 40.74, 'Mezopotamya ovasına bakan, taş evleriyle ünlü tarihi şehir.', 'TR'),
    ('edirne', 'Edirne', 41.68, 26.56, 'Selimiye Camii ve Kırkpınar yağlı güreşleriyle ünlü sınır şehri.', 'TR'),
    ('newyork', 'New York', 40.71, -74.0, 'ABD\'nin en kalabalık şehri; gökdelenleriyle ünlüdür.', 'US'),
    ('losangeles', 'Los Angeles', 34.05, -118.24, 'Film endüstrisinin merkezi Hollywood buradadır.', 'US'),
    ('chicago', 'Chicago', 41.88, -87.63, 'Michigan Gölü kıyısında; ilk gökdelen burada yapıldı.', 'US'),
    ('toronto', 'Toronto', 43.65, -79.38, 'Kanada\'nın en büyük şehri.', 'CA'),
    ('rio', 'Rio de Janeiro', -22.91, -43.17, 'Karnavalı ve Kurtarıcı İsa Heykeli ile ünlü Brezilya şehri.', 'BR'),
    ('saopaulo', 'São Paulo', -23.55, -46.63, 'Güney Amerika\'nın en kalabalık şehri.', 'BR'),
    ('sangay', 'Şanghay', 31.23, 121.47, 'Çin\'in en kalabalık şehri ve dünyanın en işlek limanlarından biri.', 'CN'),
    ('hongkong', 'Hong Kong', 22.32, 114.17, 'Dünyada en çok gökdelene sahip şehirlerden biri.', 'CN'),
    ('mumbai', 'Mumbai', 19.08, 72.88, 'Hindistan\'ın en kalabalık şehri; film endüstrisi "Bollywood" buradadır.', 'IN'),
    ('karaci', 'Karaçi', 24.86, 67.0, 'Pakistan\'ın en büyük şehri ve limanı.', 'PK'),
    ('dubai', 'Dubai', 25.2, 55.27, 'Çölün ortasında yükselen, dünyanın en yüksek binasına sahip şehir.', 'AE'),
    ('sidney', 'Sidney', -33.87, 151.21, 'Avustralya\'nın en kalabalık şehri (ama başkent değil!).', 'AU'),
    ('melbourne', 'Melbourne', -37.81, 144.96, 'Avustralya\'nın ikinci büyük şehri.', 'AU'),
    ('barselona', 'Barselona', 41.39, 2.17, 'İspanya\'nın Akdeniz kıyısındaki şehri; Sagrada Familia burada.', 'ES'),
    ('milano', 'Milano', 45.46, 9.19, 'İtalya\'nın moda ve iş merkezi.', 'IT'),
    ('venedik', 'Venedik', 45.44, 12.33, 'Sokaklar yerine kanalları olan, gondollarla gezilen şehir.', 'IT'),
    ('munih', 'Münih', 48.14, 11.58, 'Almanya\'nın güneyinde, Alpler\'e yakın büyük şehir.', 'DE'),
    ('stpetersburg', 'St. Petersburg', 59.93, 30.34, 'Rusya\'nın eski başkenti; "Kuzeyin Venedik\'i" denir.', 'RU'),
    ('cenevre', 'Cenevre', 46.2, 6.14, 'Birçok uluslararası kuruluşun merkezi olan İsviçre şehri.', 'CH'),
    ('mekke', 'Mekke', 21.39, 39.86, 'Müslümanların kutsal şehri; Kâbe buradadır.', 'SA'),
    ('osaka', 'Osaka', 34.69, 135.5, 'Japonya\'nın büyük liman ve ticaret şehri.', 'JP'),
    ('lagos', 'Lagos', 6.52, 3.38, 'Afrika\'nın en kalabalık şehirlerinden; Nijerya\'dadır.', 'NG'),
    ('kazablanka', 'Kazablanka', 33.57, -7.59, 'Fas\'ın en büyük şehri ve limanı.', 'MA'),
    ('capetown', 'Cape Town', -33.92, 18.42, 'Masa Dağı\'nın eteğinde, Afrika\'nın güney ucuna yakın şehir.', 'ZA'),
    ('iskenderiye', 'İskenderiye', 31.2, 29.92, 'Büyük İskender\'in kurduğu, antik kütüphanesiyle ünlü Mısır şehri.', 'EG'),
    ('semerkant', 'Semerkant', 39.65, 66.96, 'İpek Yolu\'nun en ünlü şehirlerinden; Timur\'un başkentiydi.', 'UZ'),
    ('selanik', 'Selanik', 40.64, 22.94, 'Atatürk\'ün doğduğu şehir; Yunanistan\'ın ikinci büyük şehri.', 'GR'),
    ('baku_x', None, 0, 0, '', None),
]

# Nehirler: (id, Türkçe ad, [Natural Earth adları], bilgi, örnek ülke, isTurkey)
RIVERS = [
    ('nil', 'Nil Nehri', ['Nile', 'El Bahr el Abyad', 'Bahr el Jebel', 'Albert Nile', 'Victoria Nile'], 'Dünyanın en uzun nehri sayılır (yaklaşık 6.650 km). Afrika\'da güneyden kuzeye akar ve Akdeniz\'e dökülür.'),
    ('amazon', 'Amazon Nehri', ['Amazonas', 'Solimões', 'Ucayali'], 'Dünyada en çok su taşıyan nehirdir. Güney Amerika\'daki dev yağmur ormanından geçer.'),
    ('mississippi', 'Mississippi Nehri', ['Mississippi'], 'Kuzey Amerika\'nın en önemli nehirlerinden; ABD\'yi kuzeyden güneye geçer.'),
    ('yangtze', 'Yangtze Nehri', ['Chang Jiang', 'Yangtze', 'Jinsha', 'Tongtian', 'Tuotuo'], 'Asya\'nın en uzun nehridir. Çin\'den geçer.'),
    ('huang', 'Sarı Irmak', ['Huang'], 'Taşıdığı sarı çamur yüzünden bu adı alır. Çin uygarlığı bu nehrin kıyısında doğdu.'),
    ('tuna', 'Tuna Nehri', ['Danube', 'Donau', 'Duna', 'Dunav', 'Dunărea'], 'Avrupa\'nın en fazla ülkeden (10 ülke) geçen nehridir. Karadeniz\'e dökülür.'),
    ('volga', 'Volga Nehri', ['Volga'], 'Avrupa\'nın en uzun nehridir. Rusya\'dan geçer ve Hazar Denizi\'ne dökülür.'),
    ('ren', 'Ren Nehri', ['Rhine', 'Rhein', 'Rhin', 'Nederrijn', 'Waal'], 'İsviçre Alpleri\'nden doğar, Almanya ve Hollanda\'dan geçip Kuzey Denizi\'ne dökülür.'),
    ('sen', 'Sen Nehri', ['Seine'], 'Paris\'in içinden geçen ünlü nehir.'),
    ('ganj', 'Ganj Nehri', ['Ganges', 'Ganga'], 'Hindistan\'ın kutsal nehri sayılır.'),
    ('indus', 'İndus Nehri', ['Indus'], 'Pakistan\'dan geçer. Çok eski bir uygarlık kıyısında kuruldu.'),
    ('kongo', 'Kongo Nehri', ['Congo', 'Lualaba'], 'Dünyanın en derin nehridir ve ekvatoru iki kez keser.'),
    ('nijer', 'Nijer Nehri', ['Niger'], 'Batı Afrika\'nın en büyük nehri; bir yay çizerek akar.'),
    ('mekong', 'Mekong Nehri', ['Mekong', 'Lancang'], 'Güneydoğu Asya\'da altı ülkeden geçer.'),
    ('zambezi', 'Zambezi Nehri', ['Zambezi', 'Zambeze'], 'Üzerinde dev Victoria Şelalesi bulunur.'),
    ('ob', 'Ob Nehri', ['Ob'], 'Sibirya\'dan Kuzey Buz Denizi\'ne akar.'),
    ('yenisey', 'Yenisey Nehri', ['Yenisey', 'Verkhniy Yenisey'], 'Sibirya\'nın en büyük nehirlerinden biridir.'),
    ('lena', 'Lena Nehri', ['Lena'], 'Sibirya\'da kışın tamamen donan büyük bir nehirdir.'),
    ('amur', 'Amur Nehri', ['Amur', 'Heilong Jiang'], 'Rusya ile Çin arasında sınır oluşturur.'),
    ('murray', 'Murray Nehri', ['Murray'], 'Avustralya\'nın en uzun nehridir.'),
    ('mackenzie', 'Mackenzie Nehri', ['Mackenzie'], 'Kanada\'nın en uzun nehridir.'),
    ('parana', 'Parana Nehri', ['Paraná'], 'Güney Amerika\'nın ikinci uzun nehri.'),
    ('orinoko', 'Orinoko Nehri', ['Orinoco'], 'Venezuela\'dan geçer ve Atlas Okyanusu\'na dökülür.'),
    ('dinyeper', 'Dinyeper Nehri', ['Dnipro', 'Dnepre', 'Dnieper', 'Dnyapro'], 'Ukrayna\'dan geçerek Karadeniz\'e dökülür.'),
    ('firat', 'Fırat Nehri', ['Firat', 'Al Furat', 'Euphrates'], 'Türkiye\'den doğar, Suriye ve Irak\'tan geçer. Mezopotamya uygarlıkları kıyısında doğdu.'),
    ('dicle', 'Dicle Nehri', ['Dicle', 'Tigris'], 'Türkiye\'den doğar, Irak\'ta Fırat ile birleşip Basra Körfezi\'ne dökülür.'),
    ('kizilirmak', 'Kızılırmak', ['Kiz?lirmak', 'Kizilirmak', 'Kızılırmak'], 'Türkiye\'nin en uzun nehridir (1.355 km). Tamamı Türkiye\'dedir ve Karadeniz\'e dökülür.'),
    ('sakarya', 'Sakarya Nehri', ['Sakarya'], 'İç Anadolu\'dan doğar ve Karadeniz\'e dökülür.'),
    ('aras', 'Aras Nehri', ['Aras'], 'Erzurum\'dan doğar ve Hazar Denizi\'ne dökülür.'),
    ('menderes', 'Büyük Menderes', ['Byk Menderes', 'Büyük Menderes'], 'Çok kıvrımlı akar; "menderes" kelimesi dünyada kıvrım anlamında kullanılır!'),
    ('ceyhan', 'Ceyhan Nehri', ['Ceyhan'], 'Çukurova\'yı sulayan ve Akdeniz\'e dökülen nehir.'),
    ('meric', 'Meriç Nehri', ['Evros', 'Maritsa', 'Meriç'], 'Türkiye ile Yunanistan arasında sınır oluşturur.'),
    ('stlawrence', 'St. Lawrence Nehri', ['St. Lawrence'], 'Büyük Göller\'i Atlas Okyanusu\'na bağlar.'),
    ('yukon', 'Yukon Nehri', ['Yukon'], 'Kanada ve Alaska\'dan geçer; altın arayıcılarıyla ünlüdür.'),
]

# Göller: (id, Türkçe ad, Natural Earth adları, bilgi, fallback lat, lon)
LAKES = [
    ('hazar', 'Hazar Denizi', ['Caspian Sea'], 'Adı deniz ama aslında dünyanın en büyük gölüdür!', 41.5, 51),
    ('baykal', 'Baykal Gölü', ['Lake Baikal'], 'Dünyanın en derin ve en eski gölüdür. Dünyanın tatlı sularının yaklaşık beşte biri buradadır.', 53.5, 108),
    ('superior', 'Superior Gölü', ['Lake Superior'], 'Büyük Göller\'in en büyüğü ve dünyanın en büyük tatlı su gölüdür.', 47.7, -87.5),
    ('victoria_g', 'Victoria Gölü', ['Lake Victoria'], 'Afrika\'nın en büyük gölüdür. Nil Nehri buradan çıkar.', -1, 33),
    ('tanganika', 'Tanganika Gölü', ['Lake Tanganyika'], 'Dünyanın en uzun tatlı su gölüdür.', -6.5, 29.8),
    ('titikaka', 'Titikaka Gölü', ['Lake Titicaca'], 'Peru ile Bolivya arasında, yaklaşık 3.800 m yükseklikte bulunur.', -15.9, -69.4),
    ('van_g', 'Van Gölü', ['Lake Van', 'Van Gölü'], 'Türkiye\'nin en büyük gölüdür. Suyu sodalıdır; içinde sadece inci kefali yaşar.', 38.63, 42.9),
    ('tuz', 'Tuz Gölü', ['Tuz Gölü', 'Lake Tuz'], 'Türkiye\'nin ikinci büyük gölüdür. Yazın suyu çekilince bembeyaz tuz tabakası kalır.', 38.75, 33.35),
    ('michigan', 'Michigan Gölü', ['Lake Michigan'], 'Tamamı ABD\'de olan tek Büyük Göl\'dür.', 44, -87),
    ('aral', 'Aral Gölü', ['Aral Sea', 'North Aral Sea', 'South Aral Sea'], 'Bir zamanlar dünyanın 4. büyük gölüydü ama sular başka yere aktarılınca çok küçüldü.', 45.2, 60),
    ('ladoga', 'Ladoga Gölü', ['Lake Ladoga'], 'Avrupa\'nın en büyük gölüdür (Rusya).', 61, 31.5),
    ('malavi', 'Malavi Gölü', ['Lake Malawi', 'Lake Nyasa'], 'İçinde yüzlerce renkli balık türü yaşar.', -12, 34.5),
    ('cad_g', 'Çad Gölü', ['Lake Chad'], 'Sahra\'nın güneyinde, büyüklüğü mevsime göre çok değişen göl.', 13.3, 14.1),
]
