# -*- coding: utf-8 -*-
"""Nederlandse inhoud voor Wereldontdekker (zelfde sleutels als content.py)."""

CAPITAL_NL = {
    'AT': 'Wenen', 'BE': 'Brussel', 'CN': 'Peking', 'EG': 'Caïro', 'DK': 'Kopenhagen',
    'DZ': 'Algiers', 'GR': 'Athene', 'ET': 'Addis Abeba', 'GB': 'Londen', 'IT': 'Rome',
    'KW': 'Koeweit-Stad', 'RU': 'Moskou', 'PL': 'Warschau', 'PT': 'Lissabon', 'RO': 'Boekarest',
    'SA': 'Riyad', 'RS': 'Belgrado', 'UA': 'Kyiv', 'US': 'Washington', 'UZ': 'Tasjkent',
    'YE': 'Sanaa', 'CZ': 'Praag', 'IQ': 'Bagdad', 'IR': 'Teheran', 'AZ': 'Bakoe',
    'MX': 'Mexico-Stad', 'BR': 'Brasilia', 'CO': 'Bogota', 'KR': 'Seoel', 'TM': 'Asjchabad',
    'KG': 'Bisjkek', 'TJ': 'Doesjanbe', 'AM': 'Jerevan', 'CY': 'Nicosia', 'MD': 'Chisinau',
    'HU': 'Boedapest', 'LU': 'Luxemburg', 'VA': 'Vaticaanstad', 'SM': 'San Marino',
    'SD': 'Khartoem', 'LB': 'Beiroet', 'SG': 'Singapore', 'MN': 'Ulaanbaatar',
    'GT': 'Guatemala-Stad', 'PA': 'Panama-Stad', 'CI': 'Yamoussoukro', 'KI': 'Zuid-Tarawa',
    'XK': 'Pristina', 'IL': 'Jeruzalem', 'PH': 'Manilla', 'KH': 'Phnom-Penh', 'FR': 'Parijs',
    'DE': 'Berlijn', 'JP': 'Tokio', 'LK': 'Colombo', 'TG': 'Lomé', 'SZ': 'Mbabane',
    'MV': 'Malé', 'TN': 'Tunis', 'LY': 'Tripoli', 'SO': 'Mogadishu', 'OM': 'Muscat',
    'AE': 'Abu Dhabi', 'BO': 'Sucre', 'KZ': 'Astana', 'MM': 'Naypyidaw', 'BH': 'Manama',
    'AF': 'Kabul', 'PK': 'Islamabad', 'SY': 'Damascus', 'TR': 'Ankara', 'GE': 'Tbilisi',
    'ZA': 'Pretoria', 'NL': 'Amsterdam', 'CH': 'Bern', 'IN': 'New Delhi', 'NP': 'Kathmandu',
}

CAPITAL_NOTE_NL = {
    'BO': 'De regering zetelt in La Paz.',
    'ZA': 'Zuid-Afrika heeft drie hoofdsteden: Pretoria, Kaapstad en Bloemfontein.',
    'NL': 'De regering werkt in Den Haag.',
    'IL': 'Of Jeruzalem de hoofdstad is, daarover zijn landen het niet eens.',
    'CI': 'De grootste stad en vroegere hoofdstad is Abidjan.',
    'NG': 'De vroegere hoofdstad en grootste stad is Lagos.',
    'TR': 'Ankara werd op 13 oktober 1923 de hoofdstad.',
    'KZ': 'In 1997 verhuisde de hoofdstad van Almaty naar Astana.',
    'BR': 'Brasilia werd helemaal nieuw gebouwd om hoofdstad te worden.',
}

SHORT_NL = {'US': 'VS', 'GB': 'Verenigd Koninkrijk', 'CD': 'Congo-Kinshasa', 'CG': 'Congo-Brazzaville',
            'AE': 'VAE', 'CF': 'Centraal-Afr. Rep.', 'DO': 'Dominicaanse Rep.', 'VC': 'St. Vincent',
            'KN': 'St. Kitts', 'ST': 'São Tomé', 'AG': 'Antigua'}
NAME_NL = {'WS': 'Samoa', 'VA': 'Vaticaanstad', 'CV': 'Kaapverdië', 'SZ': 'Eswatini', 'TR': 'Turkije'}

LANG_NL = {
    'English': 'Engels', 'French': 'Frans', 'Spanish': 'Spaans', 'Portuguese': 'Portugees',
    'Arabic': 'Arabisch', 'German': 'Duits', 'Italian': 'Italiaans', 'Russian': 'Russisch',
    'Chinese': 'Chinees', 'Japanese': 'Japans', 'Korean': 'Koreaans', 'Turkish': 'Turks',
    'Persian (Farsi)': 'Perzisch', 'Hindi': 'Hindi', 'Bengali': 'Bengaals', 'Urdu': 'Urdu',
    'Greek': 'Grieks', 'Dutch': 'Nederlands', 'Swedish': 'Zweeds', 'Norwegian Bokmål': 'Noors',
    'Danish': 'Deens', 'Finnish': 'Fins', 'Polish': 'Pools', 'Czech': 'Tsjechisch', 'Slovak': 'Slowaaks',
    'Hungarian': 'Hongaars', 'Romanian': 'Roemeens', 'Moldavian': 'Roemeens', 'Bulgarian': 'Bulgaars',
    'Serbian': 'Servisch', 'Croatian': 'Kroatisch', 'Bosnian': 'Bosnisch', 'Albanian': 'Albanees',
    'Ukrainian': 'Oekraïens', 'Belarusian': 'Wit-Russisch', 'Georgian': 'Georgisch', 'Armenian': 'Armeens',
    'Azerbaijani': 'Azerbeidzjaans', 'Kazakh': 'Kazachs', 'Uzbek': 'Oezbeeks', 'Turkmen': 'Turkmeens',
    'Kyrgyz': 'Kirgizisch', 'Tajik': 'Tadzjieks', 'Mongolian': 'Mongools', 'Hebrew': 'Hebreeuws',
    'Swahili': 'Swahili', 'Amharic': 'Amhaars', 'Indonesian': 'Indonesisch', 'Malay': 'Maleis',
    'Thai': 'Thai', 'Vietnamese': 'Vietnamees', 'Filipino': 'Filipijns', 'Khmer': 'Khmer',
    'Lao': 'Laotiaans', 'Burmese': 'Birmaans', 'Nepali': 'Nepalees', 'Tamil': 'Tamil', 'Sinhala': 'Singalees',
    'Icelandic': 'IJslands', 'Irish': 'Iers', 'Estonian': 'Ests', 'Latvian': 'Lets',
    'Lithuanian': 'Litouws', 'Slovene': 'Sloveens', 'Macedonian': 'Macedonisch', 'Maltese': 'Maltees',
    'Latin': 'Latijn', 'Luxembourgish': 'Luxemburgs', 'Catalan': 'Catalaans', 'Somali': 'Somalisch',
    'Pashto': 'Pasjtoe', 'Dari': 'Dari', 'Montenegrin': 'Montenegrijns', 'Māori': 'Maori',
    'Zulu': 'Zoeloe', 'Afrikaans': 'Afrikaans', 'Guaraní': 'Guaraní', 'Quechua': 'Quechua',
    'Aymara': 'Aymara', 'Malagasy': 'Malagassisch', 'Kinyarwanda': 'Kinyarwanda', 'Berber': 'Berbers',
    'Haitian Creole': 'Haïtiaans Creools', 'Samoan': 'Samoaans', 'Tongan': 'Tongaans', 'Fijian': 'Fijisch',
    'Greenlandic': 'Groenlands', 'Dzongkha': 'Dzongkha', 'Tigrinya': 'Tigrinya', 'Maldivian': 'Divehi',
    'Kirundi': 'Kirundi', 'Sorani': 'Koerdisch', 'Romansh': 'Reto-Romaans', 'Swiss German': 'Duits',
    'Tetum': 'Tetun', 'Tok Pisin': 'Tok Pisin', 'Shona': 'Shona', 'Xhosa': 'Xhosa',
    'Lingala': 'Lingala', 'Sango': 'Sango', 'Chewa': 'Chichewa', 'Tswana': 'Tswana',
    'Sotho': 'Sotho', 'Southern Sotho': 'Sotho', 'Swazi': 'Swazi',
}

CURRENCY_NL = {
    'TRY': 'Turkse lira', 'EUR': 'Euro', 'USD': 'Amerikaanse dollar', 'GBP': 'Britse pond',
    'JPY': 'Japanse yen', 'CNY': 'Chinese yuan', 'RUB': 'Russische roebel', 'CHF': 'Zwitserse frank',
    'XOF': 'West-Afrikaanse CFA-frank', 'XAF': 'Centraal-Afrikaanse CFA-frank', 'XCD': 'Oost-Caribische dollar',
    'INR': 'Indiase roepie', 'BRL': 'Braziliaanse real', 'ZAR': 'Zuid-Afrikaanse rand', 'KRW': 'Zuid-Koreaanse won',
    'AZN': 'Azerbeidzjaanse manat', 'SAR': 'Saoedische riyal', 'AED': 'VAE-dirham', 'MAD': 'Marokkaanse dirham',
    'EGP': 'Egyptisch pond', 'SEK': 'Zweedse kroon', 'NOK': 'Noorse kroon', 'DKK': 'Deense kroon',
    'ISK': 'IJslandse kroon', 'PLN': 'Poolse zloty', 'HUF': 'Hongaarse forint', 'CZK': 'Tsjechische kroon',
    'RON': 'Roemeense leu', 'BGN': 'Bulgaarse lev', 'UAH': 'Oekraïense hryvnja', 'MXN': 'Mexicaanse peso',
    'ARS': 'Argentijnse peso', 'CAD': 'Canadese dollar', 'AUD': 'Australische dollar',
    'NZD': 'Nieuw-Zeelandse dollar', 'ILS': 'Israëlische sjekel', 'IDR': 'Indonesische roepia',
    'THB': 'Thaise baht', 'KZT': 'Kazachse tenge', 'GEL': 'Georgische lari', 'PEN': 'Peruaanse sol',
}
CURRENCY_UNIT_NL = [
    ('dollar', 'dollar'), ('peso', 'peso'), ('franc', 'frank'), ('pound', 'pond'),
    ('dinar', 'dinar'), ('rupee', 'roepie'), ('shilling', 'shilling'), ('krona', 'kroon'),
    ('krone', 'kroon'), ('ruble', 'roebel'), ('riyal', 'rial'), ('rial', 'rial'),
    ('won', 'won'), ('dirham', 'dirham'), ('lira', 'lira'), ('manat', 'manat'),
]

FACTS_NL = {
    'TR': 'Turkije ligt in twee werelddelen: het grootste deel in Azië (Anatolië), een klein deel in Europa (Thracië). Istanbul ligt zelfs in allebei!',
    'US': 'De VS heeft 50 staten; de 50 sterren op de vlag staan voor die staten.',
    'CA': 'Canada is na Rusland het grootste land ter wereld en heeft de langste kustlijn.',
    'MX': 'Cacao, waar chocolade van gemaakt wordt, werd voor het eerst in en rond Mexico gebruikt.',
    'BR': 'Het grootste deel van het Amazone-regenwoud ligt in Brazilië. Brazilië werd 5 keer wereldkampioen voetbal.',
    'AR': 'De hoogste berg van Zuid-Amerika, de Aconcagua, staat in Argentinië. De tango komt hier ook vandaan.',
    'GB': 'Het Verenigd Koninkrijk bestaat uit Engeland, Schotland, Wales en Noord-Ierland. De bekende klokkentoren in Londen heet Big Ben.',
    'FR': 'De Eiffeltoren staat in Parijs. Frankrijk krijgt meer toeristen dan bijna elk ander land.',
    'DE': 'Duitsland heeft meer dan 20.000 kastelen en burchten. De auto werd in Duitsland uitgevonden.',
    'IT': 'Italië lijkt op de kaart op een laars! Pizza en pasta zijn beroemde Italiaanse gerechten.',
    'ES': 'In Spanje is elk jaar een tomatengevecht-feest: La Tomatina.',
    'PT': 'De Portugese zeevaarder Vasco da Gama vond als eerste de zeeroute van Europa naar India.',
    'GR': 'De Olympische Spelen werden voor het eerst in het oude Griekenland gehouden. Griekenland heeft meer dan 6.000 eilanden.',
    'NL': 'Ongeveer een derde van Nederland ligt onder de zeespiegel. Het land is beroemd om molens en tulpen.',
    'RU': 'Rusland is het grootste land ter wereld; het ligt in Europa én Azië en heeft 11 tijdzones.',
    'CN': 'De Chinese Muur is de langste muur ter wereld. Papier, het kompas en buskruit zijn in China uitgevonden.',
    'JP': 'Japan bestaat uit ongeveer 14.000 eilanden. Het wordt ook "Land van de rijzende zon" genoemd.',
    'IN': 'India is het land met de meeste inwoners ter wereld. De eerste vorm van schaken ontstond in India.',
    'AU': 'Australië is een land én een werelddeel. Kangoeroes en koala\'s wonen hier.',
    'EG': 'De piramides van Gizeh zijn ongeveer 4.500 jaar oud. De Nijl is de levensader van Egypte.',
    'ZA': 'Zuid-Afrika heeft drie hoofdsteden. Kaap de Goede Hoop ligt hier, bij de zuidpunt van Afrika.',
    'SA': 'In Saoedi-Arabië stroomt geen enkele rivier het hele jaar door. De heilige steden Mekka en Medina liggen hier.',
    'IR': 'De oude naam van Iran is Perzië. Perzische tapijten zijn wereldberoemd.',
    'IQ': 'De Eufraat en de Tigris stromen door Irak. Het schrift werd hier, in Mesopotamië, uitgevonden.',
    'AZ': 'Azerbeidzjan heet ook "Land van het vuur". Het ligt aan de Kaspische Zee en de taal lijkt heel erg op Turks.',
    'KR': 'Zuid-Korea is heel sterk in technologie. De sport taekwondo komt uit Korea.',
    'SE': 'In de zomer gaat de zon in Zweden bijna niet onder. Alfred Nobel, van de Nobelprijs, was Zweeds.',
    'NO': 'Noorwegen heeft diepe baaien aan de kust: fjorden. Je kunt er het noorderlicht zien.',
    'FI': 'Finland heet "Land van de duizend meren", maar heeft er eigenlijk meer dan 180.000!',
    'PL': 'De beroemde wetenschapper Marie Curie en sterrenkundige Copernicus kwamen uit Polen.',
    'UA': 'Oekraïne is na Rusland het grootste land van Europa. Door de vruchtbare grond heet het "de graanschuur van Europa".',
    'CH': 'Zwitserland is beroemd om horloges en chocolade. De Alpen bedekken een groot deel van het land.',
    'AT': 'De beroemde componist Mozart werd geboren in Salzburg, in Oostenrijk.',
    'BE': 'België is beroemd om chocolade en wafels. Het hoofdkwartier van de Europese Unie staat in Brussel.',
    'DK': 'LEGO is uitgevonden in Denemarken. Groenland hoort ook bij het Koninkrijk Denemarken.',
    'IE': 'Ierland heet het "Smaragdgroene Eiland" omdat het zo groen is.',
    'NZ': 'In Nieuw-Zeeland wonen meer schapen dan mensen! De kiwi-vogel is het symbool van het land.',
    'KE': 'In de natuurparken van Kenia zie je leeuwen, olifanten en giraffen. De evenaar loopt door Kenia.',
    'NG': 'Nigeria is het land met de meeste inwoners van Afrika.',
    'MA': 'Marokko ligt bij de Straat van Gibraltar maar 14 km van Europa.',
    'CO': 'Colombia is het land met de meeste vogelsoorten ter wereld.',
    'PE': 'De oude Incastad Machu Picchu ligt in Peru.',
    'CL': 'Chili is het langste en smalste land ter wereld; de Atacamawoestijn in het noorden is een van de droogste plekken op aarde.',
    'ID': 'Indonesië bestaat uit meer dan 17.000 eilanden: het grootste eilandenland ter wereld.',
    'TH': 'Het symbool van Thailand is de olifant. Vroeger heette het land Siam.',
    'KZ': 'Kazachstan is het grootste land zonder zee. De eerste ruimtereizen vertrokken vanaf Bajkonoer.',
    'PK': 'De op één na hoogste berg ter wereld, de K2, staat in Pakistan.',
    'SY': 'De hoofdstad Damascus is een van de oudste steden waar altijd mensen hebben gewoond.',
    'BG': 'Bulgarije is beroemd om rozenolie.',
    'GE': 'Georgië heeft een eigen alfabet. Het ligt aan de voet van de Kaukasus.',
    'CU': 'Cuba is het grootste eiland van de Caribische Zee.',
    'HU': 'De Rubiks kubus is uitgevonden door de Hongaarse architect Ernő Rubik.',
    'CZ': 'De astronomische klok in Praag is meer dan 600 jaar oud en werkt nog steeds.',
    'RO': 'De Karpaten liggen in Roemenië. De Donau stroomt hier de Zwarte Zee in.',
    'RS': 'De Donau en de Sava komen samen in de hoofdstad Belgrado.',
    'HR': 'De stropdas komt oorspronkelijk uit Kroatië! Voor de kust liggen meer dan 1.000 eilanden.',
    'BA': 'De brug van Mostar werd in de Ottomaanse tijd gebouwd door architect Hayreddin.',
    'AL': 'Op de vlag van Albanië staat een adelaar met twee koppen.',
    'MK': 'Het Meer van Ohrid is een van de oudste meren ter wereld.',
    'CY': 'Cyprus is het op twee na grootste eiland van de Middellandse Zee.',
    'IS': 'In IJsland liggen vulkanen en gletsjers naast elkaar. Er zijn geisers die heet water omhoog spuiten.',
    'SK': 'Slowakije heeft meer dan 6.000 grotten.',
    'SI': 'Meer dan de helft van Slovenië is bedekt met bos.',
    'UZ': 'Oude steden aan de Zijderoute, zoals Samarkand en Buchara, liggen in Oezbekistan.',
    'TM': 'In de Karakumwoestijn in Turkmenistan brandt al jaren een krater: de "Poort naar de Hel".',
    'KG': 'Meer dan 90% van Kirgizië is bergachtig. Het Manas-epos is een van de langste verhalen ter wereld.',
    'AF': 'Afghanistan heeft geen zee en de Hindoekoesj-bergen lopen dwars door het land.',
    'MN': 'In Mongolië wonen nog veel mensen als nomaden in tenten die "ger" heten. De Gobiwoestijn ligt hier.',
    'VN': 'Vietnam heeft op de kaart de vorm van een "S".',
    'PH': 'De Filipijnen bestaan uit meer dan 7.000 eilanden.',
    'MY': 'De Petronas Twin Towers in Kuala Lumpur waren ooit de hoogste gebouwen ter wereld.',
    'SG': 'Singapore is een stad én een land tegelijk.',
    'BD': 'Bangladesh heeft heel veel inwoners. De grootste rivierdelta ter wereld ligt hier.',
    'NP': 'De hoogste berg ter wereld, de Mount Everest, ligt op de grens van Nepal en China. De vlag van Nepal is de enige die niet rechthoekig is!',
    'LK': 'Sri Lanka is een eiland ten zuiden van India en is beroemd om zijn thee.',
    'KP': 'Noord-Korea is een van de meest afgesloten landen ter wereld.',
    'IL': 'De Dode Zee is het laagste punt op het land; het water is zo zout dat je blijft drijven.',
    'JO': 'Petra, een oude stad uitgehakt in de rotsen, ligt in Jordanië.',
    'LB': 'Op de vlag van Libanon staat een ceder.',
    'AE': 'Het hoogste gebouw ter wereld, de Burj Khalifa, staat in Dubai.',
    'QA': 'Qatar organiseerde het WK voetbal van 2022.',
    'KW': 'Koeweit is klein, maar heel rijk aan olie.',
    'OM': 'Oman is een van de oudste onafhankelijke landen van het Arabisch Schiereiland.',
    'YE': 'In Sanaa in Jemen staan eeuwenoude "wolkenkrabbers" van leem.',
    'VE': 'De hoogste waterval ter wereld, de Angelwaterval, ligt in Venezuela.',
    'EC': 'Ecuador is genoemd naar de evenaar die er doorheen loopt. De Galápagoseilanden horen erbij.',
    'BO': 'De zoutvlakte van Uyuni in Bolivia is de grootste zoutvlakte ter wereld.',
    'PY': 'In Paraguay spreken de meeste mensen zowel Spaans als Guaraní.',
    'UY': 'Het eerste WK voetbal was in 1930 in Uruguay, en Uruguay won!',
    'DZ': 'Algerije is het grootste land van Afrika. Het grootste deel is Saharawoestijn.',
    'TN': 'Tunesië is het noordelijkste land van Afrika.',
    'LY': 'Meer dan 90% van Libië is woestijn.',
    'SD': 'In Soedan staan meer piramides dan in Egypte!',
    'ET': 'Koffie komt oorspronkelijk uit Ethiopië.',
    'TZ': 'De hoogste berg van Afrika, de Kilimanjaro, staat in Tanzania.',
    'GH': 'Ghana is een van de landen die de meeste cacao verbouwen.',
    'SN': 'Senegal is het westelijkste land van het Afrikaanse vasteland.',
    'CM': 'Kameroen heet "Afrika in het klein" omdat er zoveel verschillende natuur is.',
    'CD': 'De Kongo, de diepste rivier ter wereld, stroomt door dit land.',
    'AO': 'De officiële taal van Angola is Portugees.',
    'MG': 'De meeste dieren op Madagaskar (zoals lemuren) leven nergens anders ter wereld.',
    'SO': 'Somalië heeft de langste kustlijn van het Afrikaanse vasteland.',
    'JM': 'Usain Bolt, een van de snelste lopers ooit, komt uit Jamaica.',
    'PA': 'Het Panamakanaal verbindt de Atlantische Oceaan met de Grote Oceaan.',
    'CR': 'Costa Rica heeft geen leger en heel rijke regenwouden.',
    'GT': 'In Guatemala staan steden van de oude Maya-beschaving.',
    'FJ': 'Fiji bestaat uit meer dan 300 eilanden.',
    'PG': 'In Papoea-Nieuw-Guinea worden meer dan 800 talen gesproken!',
    'BY': 'Wit-Rusland heeft geen zee, maar wel heel veel meren.',
    'LT': 'Aan de kust van Litouwen ligt de Koerse Schoorwal met hoge zandduinen.',
    'LV': 'De helft van Letland is bedekt met bos.',
    'EE': 'In Estland kun je online stemmen; Skype is hier ontwikkeld.',
    'MD': 'Moldavië heeft geen zee; de Gagauzische Turken wonen in dit land.',
    'AM': 'De berg Ararat is ook vanuit Armenië te zien.',
    'TJ': 'Meer dan 90% van Tadzjikistan is bergachtig; het Pamirgebergte heet "het Dak van de Wereld".',
    'MM': 'Myanmar is beroemd om duizenden pagodes met gouden koepels.',
    'KH': 'Het grootste religieuze gebouw ter wereld, Angkor Wat, ligt in Cambodja en staat op de vlag.',
    'LA': 'Laos is het enige land van Zuidoost-Azië zonder zee.',
    'NA': 'De Namibwoestijn in Namibië is waarschijnlijk de oudste woestijn ter wereld.',
    'ZW': 'De enorme Victoriawatervallen liggen op de grens van Zimbabwe en Zambia.',
    'ZM': 'Zambia is genoemd naar de rivier de Zambezi.',
    'CI': 'Ivoorkust verbouwt de meeste cacao ter wereld.',
    'ML': 'De stad Timboektoe in Mali was vroeger een belangrijk centrum van wetenschap en handel.',
    'NE': 'Niger is genoemd naar de rivier de Niger; het grootste deel is Saharawoestijn.',
    'TD': 'Tsjaad is genoemd naar het Tsjaadmeer.',
    'LU': 'Luxemburg is een van de rijkste landen ter wereld.',
    'MT': 'Op Malta staan stenen tempels die nog ouder zijn dan de piramides.',
    'ME': 'Montenegro betekent "zwarte berg", naar de donkere beboste bergen.',
    'HT': 'Haïti was het eerste land dat onafhankelijk werd door de slavernij af te schaffen (1804).',
    'DO': 'De Dominicaanse Republiek deelt het eiland Hispaniola met Haïti.',
    'VA': 'Vaticaanstad is het kleinste land ter wereld en ligt midden in Rome!',
    'MC': 'Monaco is het op één na kleinste land ter wereld en beroemd om de Formule 1-race.',
    'SM': 'San Marino is een van de oudste republieken ter wereld.',
    'LI': 'Liechtenstein is een klein bergland tussen Zwitserland en Oostenrijk.',
    'AD': 'Andorra is een klein land in de Pyreneeën, tussen Frankrijk en Spanje.',
    'MV': 'De Malediven is het laagste land ter wereld; gemiddeld maar 1,5 meter hoog.',
    'BT': 'In Bhutan meten ze geluk: het land is beroemd om het "Bruto Nationaal Geluk".',
    'TW': 'Taiwan is een eiland ten zuidoosten van China.',
    'GL': 'Groenland is het grootste eiland ter wereld en grotendeels bedekt met ijs. Het hoort bij Denemarken.',
    'SS': 'Zuid-Soedan is het jongste land ter wereld (2011).',
    'RW': 'Rwanda heet het "Land van de duizend heuvels"; hier leven berggorilla\'s.',
    'UG': 'Een deel van het Victoriameer, het grootste meer van Afrika, ligt in Oeganda.',
    'BW': 'De Okavangodelta in Botswana is een rivierdelta die niet in zee uitkomt maar in de woestijn verdwijnt.',
    'MZ': 'Op de vlag van Mozambique staat een geweer.',
    'MW': 'In het Malawimeer leven meer vissoorten dan in bijna elk ander meer.',
    'ER': 'Eritrea ligt aan de Rode Zee.',
    'DJ': 'Het Assalmeer in Djibouti is het laagste punt van Afrika.',
    'MR': 'Het "Oog van de Sahara" in Mauritanië is een reusachtige ring die je vanuit de ruimte kunt zien.',
    'GA': 'Ongeveer 85% van Gabon is bedekt met regenwoud.',
    'NI': 'Nicaragua is het grootste land van Midden-Amerika; in de meren leven zoetwaterhaaien.',
    'HN': 'In Honduras ligt de oude Mayastad Copán.',
    'SV': 'El Salvador is het kleinste land van Midden-Amerika en heet het "Land van de vulkanen".',
    'BS': 'De Bahama\'s bestaan uit meer dan 700 eilanden.',
    'TT': 'De steeldrum is uitgevonden in Trinidad en Tobago.',
    'GY': 'Guyana is het enige land in Zuid-Amerika waar Engels de officiële taal is.',
    'SR': 'Suriname is het kleinste land van Zuid-Amerika. Er wordt Nederlands gesproken!',
}

# Aardrijkskundige plekken: id -> (naam, weetje)
FEATURES_NL = {
    # bergen
    'everest': ('Mount Everest', 'De hoogste berg ter wereld: 8.849 meter! Hij staat op de grens van Nepal en China, in de Himalaya.'),
    'k2': ('K2', 'De op één na hoogste berg ter wereld (8.611 m), op de grens van Pakistan en China.'),
    'kilimanjaro': ('Kilimanjaro', 'De hoogste berg van Afrika (5.895 m). Hoewel hij bij de evenaar staat, ligt er sneeuw op de top.'),
    'aconcagua': ('Aconcagua', 'De hoogste berg van Zuid-Amerika en van de Andes (6.961 m).'),
    'denali': ('Denali', 'De hoogste berg van Noord-Amerika (6.190 m), in Alaska (VS).'),
    'elbrus': ('Elbroes', 'Wordt gezien als de hoogste berg van Europa (5.642 m), in de Kaukasus.'),
    'montblanc': ('Mont Blanc', 'De hoogste berg van de Alpen (4.806 m). De naam betekent "Witte Berg".'),
    'agri': ('Ararat (Ağrı Dağı)', 'De hoogste berg van Turkije (5.137 m). Het is een uitgedoofde vulkaan.'),
    'erciyes': ('Erciyes', 'De hoogste berg van Centraal-Anatolië (3.917 m), bij Kayseri. Je kunt er skiën.'),
    'uludag': ('Uludağ', 'De Uludağ (2.543 m) bij Bursa is een van de bekendste skigebieden van Turkije.'),
    'kackar': ('Kaçkar', 'De hoogste top van het Oost-Zwarte Zeegebergte in Turkije (3.937 m).'),
    'fuji': ('Fuji', 'De hoogste berg en het symbool van Japan (3.776 m). Het is een vulkaan.'),
    'matterhorn': ('Matterhorn', 'Deze beroemde piramidevormige Alpenberg staat op de grens van Zwitserland en Italië (4.478 m).'),
    'etna': ('Etna', 'De actiefste vulkaan van Europa, op het Italiaanse eiland Sicilië.'),
    'vezuv': ('Vesuvius', 'Deze vulkaan barstte bijna 2.000 jaar geleden uit en begroef de stad Pompeii onder as.'),
    'olimpos': ('Olympus', 'De hoogste berg van Griekenland. In oude Griekse verhalen woonden hier de goden.'),
    'maunakea': ('Mauna Kea', 'Als je deze berg op Hawaï vanaf de zeebodem meet, is hij langer dan de Everest!'),
    'vinson': ('Vinsonmassief', 'De hoogste berg van Antarctica (4.892 m).'),
    'kosciuszko': ('Mount Kosciuszko', 'De hoogste berg van Australië (2.228 m).'),
    'hasan': ('Hasan Dağı', 'De uitbarsting van deze vulkaan bij Aksaray, 9.000 jaar geleden, staat misschien op een oude muurschildering.'),
    # gebergten
    'himalaya': ('Himalaya', 'Het hoogste gebergte ter wereld. Alle bergen boven de 8.000 meter liggen in dit gebied.'),
    'and': ('Andes', 'Het langste gebergte ter wereld (ongeveer 7.000 km), langs de westkant van Zuid-Amerika.'),
    'alpler': ('Alpen', 'Het belangrijkste gebergte van Europa, door Frankrijk, Zwitserland, Italië en Oostenrijk.'),
    'kayalik': ('Rocky Mountains', 'Een groot gebergte in het westen van Noord-Amerika, van Canada tot de VS.'),
    'ural': ('Oeral', 'Dit gebergte geldt als de grens tussen Europa en Azië.'),
    'toros': ('Taurusgebergte', 'Bergen in het zuiden van Turkije, langs de Middellandse Zeekust.'),
    'kanadolu': ('Pontisch Gebergte', 'Bergen langs de Zwarte Zeekust van Turkije. Door deze bergen regent het daar veel.'),
    'kafkas': ('Kaukasus', 'Tussen de Zwarte Zee en de Kaspische Zee. De hoogste top is de Elbroes.'),
    'atlas': ('Atlasgebergte', 'In het noordwesten van Afrika, door Marokko, Algerije en Tunesië.'),
    'apalas': ('Appalachen', 'Heel oude bergen in het oosten van Noord-Amerika.'),
    'pireneler': ('Pyreneeën', 'Een natuurlijke grens tussen Frankrijk en Spanje.'),
    'karpat': ('Karpaten', 'Een boogvormig gebergte in Midden- en Oost-Europa; het grootste deel ligt in Roemenië.'),
    'bolme': ('Great Dividing Range', 'Het langste gebergte van Australië, langs de oostkust.'),
    # woestijnen
    'sahra': ('Sahara', 'De grootste hete woestijn ter wereld; bijna zo groot als de VS!'),
    'gobi': ('Gobiwoestijn', 'In Mongolië en China. Hier zijn dinosaurusfossielen gevonden.'),
    'arabistan': ('Arabische Woestijn', 'Bedekt het grootste deel van het Arabisch Schiereiland. Duinen worden tot 250 meter hoog.'),
    'atacama': ('Atacamawoestijn', 'Een van de droogste plekken op aarde; op sommige plekken regent het jarenlang niet.'),
    'kalahari': ('Kalahari', 'In het zuiden van Afrika, in Botswana en Namibië.'),
    'buyukavustralya': ('Grote Victoriawoestijn', 'De grootste woestijn van Australië.'),
    'karakum': ('Karakum', 'Deze woestijn ("zwart zand") bedekt het grootste deel van Turkmenistan.'),
    # zeeën
    'pasifik': ('Grote Oceaan (Stille Oceaan)', 'De grootste en diepste oceaan. Groter dan al het land op aarde bij elkaar!'),
    'atlas_ok': ('Atlantische Oceaan', 'De op één na grootste oceaan. Scheidt Europa en Afrika van Amerika.'),
    'hint': ('Indische Oceaan', 'De op twee na grootste oceaan, en de warmste.'),
    'arktik': ('Noordelijke IJszee', 'De kleinste en koudste oceaan. IJsberen leven op het ijs.'),
    'guney': ('Zuidelijke Oceaan', 'De oceaan rond Antarctica. Hier leven pinguïns.'),
    'akdeniz': ('Middellandse Zee', 'De zee tussen Europa, Azië en Afrika. De zuidkust van Turkije ligt eraan.'),
    'karadeniz': ('Zwarte Zee', 'De zee ten noorden van Turkije. Grote rivieren zoals de Donau stromen erin.'),
    'ege': ('Egeïsche Zee', 'Tussen Turkije en Griekenland, met heel veel eilanden.'),
    'marmara': ('Zee van Marmara', 'Een binnenzee die helemaal in Turkije ligt. Verbindt de Zwarte Zee met de Egeïsche Zee.'),
    'kizildeniz': ('Rode Zee', 'Tussen Afrika en het Arabisch Schiereiland. Beroemd om koraalriffen.'),
    'karayip': ('Caribische Zee', 'Een warme, turquoise zee ten oosten van Midden-Amerika.'),
    'kuzeydenizi': ('Noordzee', 'Tussen Groot-Brittannië en Noorwegen, Denemarken en Nederland.'),
    'baltik': ('Oostzee', 'Een zee in Noord-Europa met weinig zout water.'),
    'arap': ('Arabische Zee', 'Het noordelijke deel van de Indische Oceaan, tussen Arabië en India.'),
    'gucin': ('Zuid-Chinese Zee', 'Tussen China, Vietnam, de Filipijnen en Maleisië.'),
    'meksika': ('Golf van Mexico', 'Een grote golf omringd door de VS, Mexico en Cuba.'),
    'basra': ('Perzische Golf', 'Tussen Iran en het Arabisch Schiereiland, bekend om de olie.'),
    'japon': ('Japanse Zee', 'Tussen Japan en het Koreaans Schiereiland.'),
    # zee-engtes
    'istanbulbogazi': ('Bosporus', 'Verbindt de Zwarte Zee met de Zee van Marmara en scheidt Azië van Europa.'),
    'canakkale': ('Dardanellen', 'Verbindt de Zee van Marmara met de Egeïsche Zee.'),
    'cebelitarik': ('Straat van Gibraltar', 'Verbindt de Middellandse Zee met de Atlantische Oceaan en scheidt Europa van Afrika.'),
    'panama_k': ('Panamakanaal', 'Door mensen gegraven kanaal waardoor schepen van de Atlantische naar de Grote Oceaan varen.'),
    'suveys': ('Suezkanaal', 'Verbindt de Middellandse Zee met de Rode Zee; schepen hoeven niet om Afrika heen.'),
    'bering': ('Beringstraat', 'Scheidt Azië van Noord-Amerika; op het smalste punt maar 82 km breed.'),
    # bezienswaardigheden
    'eyfel': ('Eiffeltoren', 'Deze ijzeren toren in Parijs werd in 1889 gebouwd en is 330 meter hoog.'),
    'piramitler': ('Piramides van Gizeh', 'Het enige van de Zeven Wereldwonderen van de Oudheid dat nog bestaat.'),
    'cinseddi': ('Chinese Muur', 'Deze muur van duizenden kilometers werd gebouwd om China te beschermen.'),
    'ozgurluk': ('Vrijheidsbeeld', 'Dit beeld in New York was een cadeau van Frankrijk aan de VS.'),
    'tacmahal': ('Taj Mahal', 'Dit witte marmeren gebouw in India liet een keizer bouwen voor zijn vrouw.'),
    'kolezyum': ('Colosseum', 'In deze reusachtige arena in Rome pasten ongeveer 50.000 mensen.'),
    'machupicchu': ('Machu Picchu', 'Een oude Incastad hoog in de Andes.'),
    'sidneyopera': ('Sydney Opera House', 'Met zijn dak als zeilen het beroemdste gebouw van Australië.'),
    'kurtarici': ('Christus de Verlosser', 'Een reusachtig beeld op een berg in Rio de Janeiro.'),
    'petra': ('Petra', 'Een oude stad in Jordanië, uitgehakt in roze rotsen.'),
    'ayasofya': ('Hagia Sophia (Ayasofya)', 'Dit gebouw in Istanbul is ongeveer 1.500 jaar oud en beroemd om de enorme koepel.'),
    'kapadokya': ('Cappadocië', 'Gebied rond Nevşehir, beroemd om de "feeënschoorstenen" en heteluchtballonnen.'),
    'pamukkale': ('Pamukkale', 'Spierwitte kalkterrassen in Denizli die op een kasteel van katoen lijken.'),
    'nemrut': ('Nemrut Dağı', 'Een berg in Adıyaman met reusachtige stenen beelden op de top.'),
    'gobeklitepe': ('Göbekli Tepe', 'Deze plek bij Şanlıurfa is ongeveer 12.000 jaar oud: de oudste bekende tempel.'),
    'efes': ('Efeze', 'Oude stad bij İzmir met de beroemde Bibliotheek van Celsus.'),
    'bigben': ('Big Ben', 'De naam van de grote klok in de beroemde klokkentoren van Londen.'),
    'pisa': ('Toren van Pisa', 'Deze klokkentoren in Italië staat scheef door de zachte grond.'),
    'angkor': ('Angkor Wat', 'Het grootste religieuze gebouw ter wereld, in Cambodja.'),
    'chichenitza': ('Chichén Itzá', 'Een Maya-trappiramide in Mexico.'),
    'stonehenge': ('Stonehenge', 'Enorme stenen in een cirkel in Engeland, 5.000 jaar oud.'),
    'burj': ('Burj Khalifa', 'Het hoogste gebouw ter wereld (828 m), in Dubai.'),
    'niagara': ('Niagarawatervallen', 'Beroemde, krachtige watervallen op de grens van de VS en Canada.'),
    'victoriaf': ('Victoriawatervallen', 'Watervallen in de Zambezi; de lokale naam betekent "Donderende Rook".'),
    'angel': ('Angelwaterval', 'De hoogste waterval ter wereld (979 m), in Venezuela.'),
    'kanyon': ('Grand Canyon', 'Een reusachtige kloof die de Colorado-rivier in miljoenen jaren uitsleet (VS).'),
    'setresifi': ('Great Barrier Reef', 'Het grootste koraalrif ter wereld, bij Australië; te zien vanuit de ruimte.'),
    'amazon_orman': ('Amazone-regenwoud', 'Het grootste regenwoud ter wereld, ook wel "de longen van de aarde".'),
    'kuzeykutbu': ('Noordpool', 'Het noordelijkste punt van de aarde. Daar is geen land, alleen bevroren zee.'),
    'olu_deniz': ('Dode Zee', 'Het laagste punt op het land (430 m onder zeeniveau). Je blijft drijven in het water.'),
    # steden
    'istanbul': ('Istanbul', 'De grootste stad van Turkije. Ligt in twee werelddelen en was hoofdstad van drie grote rijken.'),
    'izmir': ('İzmir', 'De derde stad van Turkije, aan de Egeïsche Zee.'),
    'antalya': ('Antalya', 'Aan de Middellandse Zee; de toeristenhoofdstad van Turkije.'),
    'bursa': ('Bursa', 'Een van de eerste hoofdsteden van het Ottomaanse Rijk, bekend om İskender kebab en de Uludağ.'),
    'trabzon': ('Trabzon', 'Aan de Zwarte Zee, vlak bij het Sümela-klooster en het meer Uzungöl.'),
    'konya': ('Konya', 'De grootste provincie van Turkije. Mevlana (Rumi) woonde hier.'),
    'adana': ('Adana', 'Aan de rivier de Seyhan, in de vruchtbare Çukurova-vlakte.'),
    'gaziantep': ('Gaziantep', 'Wereldberoemd om baklava, pistache en lekker eten.'),
    'erzurum': ('Erzurum', 'Een van de koudste steden van Turkije; hier ligt skigebied Palandöken.'),
    'van': ('Van', 'Aan het Vanmeer, het grootste meer van Turkije. Bekend om de Vankat.'),
    'diyarbakir': ('Diyarbakır', 'Aan de Tigris, met een van de langste stadsmuren ter wereld.'),
    'samsun': ('Samsun', 'Hier kwam Atatürk op 19 mei 1919 aan land om de Onafhankelijkheidsoorlog te beginnen.'),
    'eskisehir': ('Eskişehir', 'Studentenstad aan de rivier de Porsuk, bekend om universiteiten en meerschuim.'),
    'kayseri': ('Kayseri', 'Aan de voet van de Erciyes; bekend om mantı, pastırma en handel.'),
    'mardin': ('Mardin', 'Historische stad met stenen huizen, met uitzicht over de Mesopotamische vlakte.'),
    'edirne': ('Edirne', 'Grensstad, beroemd om de Selimiye-moskee en het Kırkpınar-olieworstelen.'),
    'newyork': ('New York', 'De grootste stad van de VS, beroemd om wolkenkrabbers.'),
    'losangeles': ('Los Angeles', 'Hier ligt Hollywood, het centrum van de filmwereld.'),
    'chicago': ('Chicago', 'Aan het Michiganmeer; hier werd de eerste wolkenkrabber gebouwd.'),
    'toronto': ('Toronto', 'De grootste stad van Canada.'),
    'rio': ('Rio de Janeiro', 'Braziliaanse stad, beroemd om het carnaval en het Christusbeeld.'),
    'saopaulo': ('São Paulo', 'De grootste stad van Zuid-Amerika.'),
    'sangay': ('Shanghai', 'De grootste stad van China en een van de drukste havens ter wereld.'),
    'hongkong': ('Hongkong', 'Een van de steden met de meeste wolkenkrabbers ter wereld.'),
    'mumbai': ('Mumbai', 'De grootste stad van India; hier zit de filmindustrie "Bollywood".'),
    'karaci': ('Karachi', 'De grootste stad en haven van Pakistan.'),
    'dubai': ('Dubai', 'Een stad midden in de woestijn met het hoogste gebouw ter wereld.'),
    'sidney': ('Sydney', 'De grootste stad van Australië (maar niet de hoofdstad!).'),
    'melbourne': ('Melbourne', 'De tweede stad van Australië.'),
    'barselona': ('Barcelona', 'Spaanse stad aan de Middellandse Zee; hier staat de Sagrada Família.'),
    'milano': ('Milaan', 'Het centrum van mode en zaken in Italië.'),
    'venedik': ('Venetië', 'Een stad met grachten in plaats van straten; je vaart er in gondels.'),
    'munih': ('München', 'Grote stad in het zuiden van Duitsland, dicht bij de Alpen.'),
    'stpetersburg': ('Sint-Petersburg', 'De vroegere hoofdstad van Rusland; ook wel "Venetië van het Noorden".'),
    'cenevre': ('Genève', 'Zwitserse stad met veel internationale organisaties.'),
    'mekke': ('Mekka', 'De heilige stad van moslims; hier staat de Kaaba.'),
    'osaka': ('Osaka', 'Grote haven- en handelsstad in Japan.'),
    'lagos': ('Lagos', 'Een van de grootste steden van Afrika, in Nigeria.'),
    'kazablanka': ('Casablanca', 'De grootste stad en haven van Marokko.'),
    'capetown': ('Kaapstad', 'Aan de voet van de Tafelberg, dicht bij de zuidpunt van Afrika.'),
    'iskenderiye': ('Alexandrië', 'Egyptische stad, gesticht door Alexander de Grote, beroemd om de oude bibliotheek.'),
    'semerkant': ('Samarkand', 'Een van de beroemdste steden aan de Zijderoute; de hoofdstad van Timur.'),
    'selanik': ('Thessaloniki', 'De stad waar Atatürk geboren is; de tweede stad van Griekenland.'),
    # rivieren
    'nil': ('Nijl', 'Wordt gezien als de langste rivier ter wereld (ongeveer 6.650 km). Stroomt in Afrika van zuid naar noord, naar de Middellandse Zee.'),
    'amazon': ('Amazone', 'De rivier met het meeste water ter wereld. Stroomt door het enorme regenwoud in Zuid-Amerika.'),
    'mississippi': ('Mississippi', 'Een van de belangrijkste rivieren van Noord-Amerika; stroomt van noord naar zuid door de VS.'),
    'yangtze': ('Jangtsekiang', 'De langste rivier van Azië, door China.'),
    'huang': ('Gele Rivier', 'Heet zo door de gele modder. De Chinese beschaving ontstond aan deze rivier.'),
    'tuna': ('Donau', 'Stroomt door de meeste landen van Europa (10!) en mondt uit in de Zwarte Zee.'),
    'volga': ('Wolga', 'De langste rivier van Europa. Stroomt door Rusland naar de Kaspische Zee.'),
    'ren': ('Rijn', 'Ontspringt in de Zwitserse Alpen, stroomt door Duitsland en Nederland naar de Noordzee.'),
    'sen': ('Seine', 'De beroemde rivier die door Parijs stroomt.'),
    'ganj': ('Ganges', 'De heilige rivier van India.'),
    'indus': ('Indus', 'Stroomt door Pakistan. Aan de oevers ontstond een heel oude beschaving.'),
    'kongo': ('Kongo', 'De diepste rivier ter wereld; hij kruist de evenaar twee keer.'),
    'nijer': ('Niger', 'De grootste rivier van West-Afrika; hij stroomt in een grote boog.'),
    'mekong': ('Mekong', 'Stroomt door zes landen in Zuidoost-Azië.'),
    'zambezi': ('Zambezi', 'In deze rivier liggen de enorme Victoriawatervallen.'),
    'ob': ('Ob', 'Stroomt door Siberië naar de Noordelijke IJszee.'),
    'yenisey': ('Jenisej', 'Een van de grootste rivieren van Siberië.'),
    'lena': ('Lena', 'Een grote rivier in Siberië die in de winter helemaal bevriest.'),
    'amur': ('Amoer', 'Vormt de grens tussen Rusland en China.'),
    'murray': ('Murray', 'De langste rivier van Australië.'),
    'mackenzie': ('Mackenzie', 'De langste rivier van Canada.'),
    'parana': ('Paraná', 'De op één na langste rivier van Zuid-Amerika.'),
    'orinoko': ('Orinoco', 'Stroomt door Venezuela naar de Atlantische Oceaan.'),
    'dinyeper': ('Dnjepr', 'Stroomt door Oekraïne naar de Zwarte Zee.'),
    'firat': ('Eufraat', 'Ontspringt in Turkije en stroomt door Syrië en Irak. De eerste beschavingen van Mesopotamië ontstonden hier.'),
    'dicle': ('Tigris', 'Ontspringt in Turkije en komt in Irak samen met de Eufraat; mondt uit in de Perzische Golf.'),
    'kizilirmak': ('Kızılırmak', 'De langste rivier van Turkije (1.355 km). Ligt helemaal in Turkije en stroomt naar de Zwarte Zee.'),
    'sakarya': ('Sakarya', 'Ontspringt in Centraal-Anatolië en stroomt naar de Zwarte Zee.'),
    'aras': ('Aras', 'Ontspringt bij Erzurum en stroomt naar de Kaspische Zee.'),
    'menderes': ('Grote Menderes', 'Kronkelt enorm; het woord "meander" (kronkel) komt van deze rivier!'),
    'ceyhan': ('Ceyhan', 'Bevloeit de Çukurova-vlakte en stroomt naar de Middellandse Zee.'),
    'meric': ('Evros (Meriç)', 'Vormt de grens tussen Turkije en Griekenland.'),
    'stlawrence': ('Saint Lawrence', 'Verbindt de Grote Meren met de Atlantische Oceaan.'),
    'yukon': ('Yukon', 'Stroomt door Canada en Alaska; bekend van de goudzoekers.'),
    # meren
    'hazar': ('Kaspische Zee', 'Het heet een zee, maar eigenlijk is het het grootste meer ter wereld!'),
    'baykal': ('Baikalmeer', 'Het diepste en oudste meer ter wereld. Ongeveer een vijfde van al het zoete water op aarde zit hierin.'),
    'superior': ('Bovenmeer', 'Het grootste van de Grote Meren en het grootste zoetwatermeer ter wereld.'),
    'victoria_g': ('Victoriameer', 'Het grootste meer van Afrika. De Nijl begint hier.'),
    'tanganika': ('Tanganyikameer', 'Het langste zoetwatermeer ter wereld.'),
    'titikaka': ('Titicacameer', 'Tussen Peru en Bolivia, op ongeveer 3.800 meter hoogte.'),
    'van_g': ('Vanmeer', 'Het grootste meer van Turkije. Het water is sodahoudend; er leeft maar één vissoort.'),
    'tuz': ('Zoutmeer (Tuz Gölü)', 'Het op één na grootste meer van Turkije. In de zomer blijft er een spierwitte zoutlaag over.'),
    'michigan': ('Michiganmeer', 'Het enige van de Grote Meren dat helemaal in de VS ligt.'),
    'aral': ('Aralmeer', 'Was ooit het op drie na grootste meer ter wereld, maar is heel klein geworden doordat het water werd weggeleid.'),
    'ladoga': ('Ladogameer', 'Het grootste meer van Europa (Rusland).'),
    'malavi': ('Malawimeer', 'Hier leven honderden soorten kleurrijke vissen.'),
    'cad_g': ('Tsjaadmeer', 'Ten zuiden van de Sahara; de grootte verandert heel erg per seizoen.'),
}
